apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: broker-secret
  namespace: nexus-prod
spec:
  encryptedData:
    REDIS_PASSWORD: AgC9a0O+ALbskN14ciDJ1LC7+EUHR4sQjYPDRwXlMoa08t7jTTe8xsR1DahVJQUgnhZAJr5nk8lK6MyNGOuYsscm1DVvoR3pBn4SdM5PhucyA9Vd5vcKN0B2h348RhMZ6ehu884V3FeaZoiKcHo01qDG20Zdg3Ym8Jv6O6NDyQr64EleFHxYTlnX/9mL8J6hQxHl5sa/V5s4PyeiXZ+1GlydECjTu7muADP55RXE/HaAK6eR4BjFvR8ZBLFAOxcTveJaiLIWxklPVOKOqfNmirCfqOhoK+F/wTgK5D5GB5NWlcVzp92V3pet7XM426ozznRc7qnX+9NJy/R3VzOSdaKjBccD86m/BIq7DGwlrwJROgtX//VZHBly50t46dJCcDUOMfi9pFs3fpL6TlfkFCBJIRFWNXaZzjIYSZWIcW+dlCqKoyUeDSgWokK/bl4Cm7k+hbUuCcC5aaPviirJVLUTMBSXOYorKf5U7V8H0rYIO6cJaYhDWYlsJduD/Rk44FK9pTHTvPXStTB4ah2TQ5vkxKo6TQFv61hQDGnVdHsrSDMIQWrJVyOR0AOv2fbS/Ld0r4D25+JKvqmD/sn9PEDm1IZVVfd5T5vXMhBteKQGQurKAj3sS5/rwDZlifXh8CajwDPjFKSmJXmzFYsSuLau+Mp1Bs4Zi7VUqkecFh+R4jMth4ClqD+B356mBfwMUjEyApKYpvTGJEjdgMraRDQ=
  template:
    metadata:
      name: broker-secret
      namespace: nexus-prod
