apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: facade-secret
  namespace: nexus-prod
spec:
  encryptedData:
    SENTRY_DSN: AgDC8KxbVX+5k0728HMT0PUXE7ddlDSTBsTC0KQw2XzgGmKwBrhyxiT3BgL91ujrqnM3wWVmbHSabcS/5NRx3i8sNAbsa/tgz4IcwsiEHMGcPBXfgkvmb8pQbGaeh7JLlK3hIxc/R1nvqIZXqYPFNLq4Qy6r9iIAea5dbG2Kygw3Fmwee6LUklUxVlC86DIrFAepq4oprI6BPVSdRBlH9kw7Xwr4Nz+G6V86bjGt73/N0l52oNzNi5ujal5aR3+jtfon3dDB6kwZjbNFU7aE9xL82PktePlhHNiBeuCt8ZI2kJ6sIzpYR/+X781UwXAsfhAauXa+83tY6yj8ujTgvMKXSYam9fvFH6GosIZvKX5lxiXGE/Co+DbisMKi8AyfgOIbb58pbT615Sl1Cia65Y24laAk2yYc/8sNeOGhFyiPLoz3a4Q1fiMw6igobRSb7vAz2PYlhSUxMt3SwTTOg5Ir0dwYnB2+ZMZU5sMyGaJPTr5rkrste0FhUeLr14UNPrTGaDF/D2RMJjUZOdawZ+3MjVfGbui0rlJk9N0K9DL7cMg+thiXwvLPgOKWuO5VjqXX4veEfcLJdT7eihZ6czqYJ1wi5zALsJWHWh1/NdjgDNuCSWic3iobb752Mlgo/nqWgdgGujnLZ4GGFd73cTOw2meeG78aKSQ5a9BkproZ0uJOYPmPI/gtZ9d9sCY0ynmE70Z+qOPMhDUagu8ZQgLiw8Tf/3erx94292blkbTtGuVzsYyssHy9RdFcCWV5A8ppzbF31ufMwNFayvUBEUqIrKOuqEtvHEq7hD7Q1u4qxPT6a7pvdY1DCC/gFtx/8g==
  template:
    metadata:
      name: facade-secret
      namespace: nexus-prod
