apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: realtime-secret
  namespace: nexus-prod
spec:
  encryptedData:
    REDIS_PASSWORD: AgBetbEkyTW5ygO3q8CkVFp3fXTY5cgVW4ND6HaC8GxjjhUCMkoBEiqn6jisxiqIEWIgtlxSBAY3F3LvL2f3XX1a907Odne6PElalkrKJtxQhz15TxziYqXu3zsDTUBL8G3vMB37Y8GXJ9gMMcdaPtqzrjCdbr/5PKFI+bl7o7keDUpkrwnuS8P9N7ydeEU+/o4f5NdEHkAZ+jRwXrOCL4+HhdytlPZ7fEFwPiR3ek04a9/njwAB0TdOas/5ku2YAiUIcDma/DTgWZFytApFfScVCpLXbiidT3ADN/ck0YgvtTExiCqJIt01MMNjA7HLrpClNdHy8EAqt9hu6C+QjXZDOXL8eLBYDwPKdNCNl3DTwBSqqui5JeImLNS0TJEr+UwEudq9VoglxvVdc1i9qy/EkUEhG22tBywS4b4nS4DniwC4MM6yQBMLTErQtfqeXkV3BkZ0M5celJxUzUq6KwKmQQn3ed0Hm79szjpvUAGUh65il2xXVWvxZ6vkFpYrcExoAHItjzqXMaMEz9TBRGEEdpBkNzCy9YNVV8JZIgunQ9dSUZSt0Zl2rsI8nYpHcLBF3P+iDxplu/m00aXXyKg6g2d40eaC2jKWn02nTcgnmxbMy+jK7T7BEZYxnFWxkchvdd4GD99XJ5w/HlpEXUh5vVd5k63NkRh/3D88FsERYyunUFKVKtdE6budG/DhsYqp8alZgBPLnMw4duvB/Ik=
  template:
    metadata:
      name: realtime-secret
      namespace: nexus-prod
