apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: realtime-secret
  namespace: nexus-prod
spec:
  encryptedData:
    BROKER_PASSWORD: AgB0ZjwF9U0ogx2GKrHY4W82x/mQ475p92mKTQZlWnFslQ1vHesJPDKdxS+RfC4SUTIYAtzMTn1A8SAlOnL8FrMeA7wUYovU72/hkhnuX03/ViTvdhwyLTBhPZ73UXu3KpkPpJdm4J5P0IuISFJ1sJE/efAVbIctemXYOsk7WVDXKG8aPMLxOfvB1bCVZKRJfgtpMM7T60SRepXxF17JcFPIRmnfh4LuknlzTOXU7dRJUohP/OKG1PcwkrbVwSXXy8UhFRkdi6D8IflcJe5j8PHqy62cb8yYzhHQ13RaAS+rN/T8+rKQvfajAcCx7roufQzNndjS43vcoHi0q9RKmmk8Kyo3Fs5OKr2IL8O+dfUfF7rMNm2+H53t61Qt4pmGNSXsUaecYAamGtZf3vZoKQbptcLACeBslPOmn16NehzYv65Fro7e00AjOrrwXhyO7MEWRjR3STleUytcKYf6aPFPPIG0Z4janUwactaMl73yQ0AHEE0QwXDCbAr9rtlFzbMvAtztWVtgVAxiIs14a4TIQ6E9O+8/bIPTupWTvF9RyeiIKu/GBEdelAV4TXoiF+v416651rp9T83ggdPZPsOOMRT9QmbnwzDhN1qKvSvuDkkju2VSIWg5tO5qPtpfwFcMZXEhUGyvfOfnGfnalnSKzpA4euTfuf+AvSYqOsnOwXgIDspry3Q3Pz6MAvXJSphHTvLiOgZwo9SuzLaOrq4=
  template:
    metadata:
      name: realtime-secret
      namespace: nexus-prod
