// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockBoardRep

import (
	context "context"

	db "github.com/go-park-mail-ru/2026_1_Clac_Clac/internal/db"
	mock "github.com/stretchr/testify/mock"

	models "github.com/go-park-mail-ru/2026_1_Clac_Clac/internal/board/models"

	uuid "github.com/google/uuid"
)

// BoardRepository is an autogenerated mock type for the BoardRepository type
type BoardRepository struct {
	mock.Mock
}

// AddEmptyBoard provides a mock function with given fields: ctx, baord, userID
func (_m *BoardRepository) AddEmptyBoard(ctx context.Context, baord db.Board, userID uuid.UUID) error {
	ret := _m.Called(ctx, baord, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddEmptyBoard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.Board, uuid.UUID) error); ok {
		r0 = rf(ctx, baord, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBoards provides a mock function with given fields: ctx, userID
func (_m *BoardRepository) GetBoards(ctx context.Context, userID uuid.UUID) ([]models.Board, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBoards")
	}

	var r0 []models.Board
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Board, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Board); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Board)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBoardRepository creates a new instance of BoardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBoardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BoardRepository {
	mock := &BoardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
