// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: contracts/authorization/authorization.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtendSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendSessionRequest) Reset() {
	*x = ExtendSessionRequest{}
	mi := &file_contracts_authorization_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendSessionRequest) ProtoMessage() {}

func (x *ExtendSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_authorization_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendSessionRequest.ProtoReflect.Descriptor instead.
func (*ExtendSessionRequest) Descriptor() ([]byte, []int) {
	return file_contracts_authorization_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *ExtendSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ExtendSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendSessionResponse) Reset() {
	*x = ExtendSessionResponse{}
	mi := &file_contracts_authorization_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendSessionResponse) ProtoMessage() {}

func (x *ExtendSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_authorization_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendSessionResponse.ProtoReflect.Descriptor instead.
func (*ExtendSessionResponse) Descriptor() ([]byte, []int) {
	return file_contracts_authorization_authorization_proto_rawDescGZIP(), []int{1}
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_contracts_authorization_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_authorization_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_contracts_authorization_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_contracts_authorization_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_authorization_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_contracts_authorization_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetUserLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLinkRequest) Reset() {
	*x = GetUserLinkRequest{}
	mi := &file_contracts_authorization_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLinkRequest) ProtoMessage() {}

func (x *GetUserLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_authorization_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLinkRequest.ProtoReflect.Descriptor instead.
func (*GetUserLinkRequest) Descriptor() ([]byte, []int) {
	return file_contracts_authorization_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserLinkRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetUserLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLinkResponse) Reset() {
	*x = GetUserLinkResponse{}
	mi := &file_contracts_authorization_authorization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLinkResponse) ProtoMessage() {}

func (x *GetUserLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_authorization_authorization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLinkResponse.ProtoReflect.Descriptor instead.
func (*GetUserLinkResponse) Descriptor() ([]byte, []int) {
	return file_contracts_authorization_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserLinkResponse) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_contracts_authorization_authorization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_authorization_authorization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_contracts_authorization_authorization_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_contracts_authorization_authorization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_authorization_authorization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_contracts_authorization_authorization_proto_rawDescGZIP(), []int{7}
}

var File_contracts_authorization_authorization_proto protoreflect.FileDescriptor

const file_contracts_authorization_authorization_proto_rawDesc = "" +
	"\n" +
	"+contracts/authorization/authorization.proto\x12\x04auth\"5\n" +
	"\x14ExtendSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x17\n" +
	"\x15ExtendSessionResponse\"3\n" +
	"\x14CreateSessionRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"3\n" +
	"\x12GetUserLinkRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"2\n" +
	"\x13GetUserLinkResponse\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\"5\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x17\n" +
	"\x15DeleteSessionResponse2\xaf\x02\n" +
	"\vAuthService\x12H\n" +
	"\rCreateSession\x12\x1a.auth.CreateSessionRequest\x1a\x1b.auth.CreateSessionResponse\x12B\n" +
	"\vGetUserLink\x12\x18.auth.GetUserLinkRequest\x1a\x19.auth.GetUserLinkResponse\x12H\n" +
	"\rDeleteSession\x12\x1a.auth.DeleteSessionRequest\x1a\x1b.auth.DeleteSessionResponse\x12H\n" +
	"\rExtendSession\x12\x1a.auth.ExtendSessionRequest\x1a\x1b.auth.ExtendSessionResponseB\x1bZ\x19./pkg/contracts/auth;authb\x06proto3"

var (
	file_contracts_authorization_authorization_proto_rawDescOnce sync.Once
	file_contracts_authorization_authorization_proto_rawDescData []byte
)

func file_contracts_authorization_authorization_proto_rawDescGZIP() []byte {
	file_contracts_authorization_authorization_proto_rawDescOnce.Do(func() {
		file_contracts_authorization_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_authorization_authorization_proto_rawDesc), len(file_contracts_authorization_authorization_proto_rawDesc)))
	})
	return file_contracts_authorization_authorization_proto_rawDescData
}

var file_contracts_authorization_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_contracts_authorization_authorization_proto_goTypes = []any{
	(*ExtendSessionRequest)(nil),  // 0: auth.ExtendSessionRequest
	(*ExtendSessionResponse)(nil), // 1: auth.ExtendSessionResponse
	(*CreateSessionRequest)(nil),  // 2: auth.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 3: auth.CreateSessionResponse
	(*GetUserLinkRequest)(nil),    // 4: auth.GetUserLinkRequest
	(*GetUserLinkResponse)(nil),   // 5: auth.GetUserLinkResponse
	(*DeleteSessionRequest)(nil),  // 6: auth.DeleteSessionRequest
	(*DeleteSessionResponse)(nil), // 7: auth.DeleteSessionResponse
}
var file_contracts_authorization_authorization_proto_depIdxs = []int32{
	2, // 0: auth.AuthService.CreateSession:input_type -> auth.CreateSessionRequest
	4, // 1: auth.AuthService.GetUserLink:input_type -> auth.GetUserLinkRequest
	6, // 2: auth.AuthService.DeleteSession:input_type -> auth.DeleteSessionRequest
	0, // 3: auth.AuthService.ExtendSession:input_type -> auth.ExtendSessionRequest
	3, // 4: auth.AuthService.CreateSession:output_type -> auth.CreateSessionResponse
	5, // 5: auth.AuthService.GetUserLink:output_type -> auth.GetUserLinkResponse
	7, // 6: auth.AuthService.DeleteSession:output_type -> auth.DeleteSessionResponse
	1, // 7: auth.AuthService.ExtendSession:output_type -> auth.ExtendSessionResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_authorization_authorization_proto_init() }
func file_contracts_authorization_authorization_proto_init() {
	if File_contracts_authorization_authorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_authorization_authorization_proto_rawDesc), len(file_contracts_authorization_authorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_authorization_authorization_proto_goTypes,
		DependencyIndexes: file_contracts_authorization_authorization_proto_depIdxs,
		MessageInfos:      file_contracts_authorization_authorization_proto_msgTypes,
	}.Build()
	File_contracts_authorization_authorization_proto = out.File
	file_contracts_authorization_authorization_proto_goTypes = nil
	file_contracts_authorization_authorization_proto_depIdxs = nil
}
