namespace: "nexus-prod"

ingress:
  enabled: true
  host: clac-clac.ru

docs:
  enabled: true
  image: nginx:alpine
  port: 80
  host: docs.clac-clac.ru
  resources:
    limits:
      memory: "64Mi"
      cpu: "10m"

frontend:
  enabled: true
  image: nginx:alpine
  port: 80
  static: /home/ubuntu
  resources:
    limits:
      memory: "64Mi"
      cpu: "10m"

postgres:
  image: postgres:17-alpine
  port: 5432
  resources:
    limits: { memory: "128Mi", cpu: "50m" }
    requests: { memory: "64Mi", cpu: "10m" }

redis:
  image: redis:7-alpine
  port: 6379
  resources:
    limits: { memory: "64Mi", cpu: "50m" }
    requests: { memory: "32Mi", cpu: "10m" }

services:
  facade:
    enabled: true
    hasConfig: true
    hasSecrets: true
    image: nisakoo/nexus-facade:sha-43cbe76
    port: 8080
    database:
      enabled: false
    redis:
      enabled: false
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
      requests:
        memory: "64Mi"
        cpu: "10m"

  rate-limiter:
    enabled: true
    hasConfig: true
    hasSecrets: true
    image: nisakoo/nexus-rate_limiter:sha-43cbe76
    port: 8080
    database:
      enabled: false
    redis:
      enabled: true
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
      requests:
        memory: "32Mi"
        cpu: "10m"

  authorization:
    enabled: true
    hasConfig: true
    hasSecrets: true
    image: nisakoo/nexus-authorization:sha-43cbe76
    port: 8080
    database:
      enabled: false
    redis:
      enabled: true
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
      requests:
        memory: "32Mi"
        cpu: "10m"

  user:
    enabled: true
    hasConfig: true
    hasSecrets: true
    image: nisakoo/nexus-user:sha-43cbe76
    port: 8080
    database:
      enabled: true
    redis:
      enabled: false
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
      requests:
        memory: "64Mi"
        cpu: "10m"

  mail-sender:
    enabled: true
    hasConfig: true
    hasSecrets: true
    image: nisakoo/nexus-mail_sender:sha-43cbe76
    port: 8080
    database:
      enabled: false
    redis:
      enabled: true
    resources:
      limits:
        memory: "64Mi"
        cpu: "10m"
      requests:
        memory: "32Mi"
        cpu: "10m"

  board:
    enabled: true
    hasConfig: true
    hasSecrets: true
    image: nisakoo/nexus-board:sha-43cbe76
    port: 8080
    database:
      enabled: true
    redis:
      enabled: true
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
      requests:
        memory: "32Mi"
        cpu: "10m"

  appeal:
    enabled: true
    hasConfig: true
    hasSecrets: true
    image: nisakoo/nexus-appeal:sha-43cbe76
    port: 8080
    database:
      enabled: true
    redis:
      enabled: false
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
      requests:
        memory: "32Mi"
        cpu: "10m"
