namespace: "nexus-prod"

ingress:
  enabled: true
  host: clac-clac.ru

frontend:
  enabled: true
  image: nginx:alpine
  port: 80
  static: /home/ubuntu/public
  resources:
    limits:
      memory: "64Mi"
      cpu: "10m"

postgres:
  image: postgres:17-alpine
  port: 5432
  resources:
    limits: { memory: "256Mi", cpu: "100m" }

redis:
  image: redis:7-alpine
  port: 6379
  resources:
    limits: { memory: "256Mi", cpu: "100m" }

services:
  facade:
    enabled: true
    hasConfig: true
    hasSecrets: true
    image: nisakoo/nexus-facade:latest
    port: 8080
    database:
      enabled: false
    redis:
      enabled: false
    resources:
      limits:
        memory: "256Mi"
        cpu: "100m"

  rate-limiter:
    enabled: true
    hasConfig: true
    hasSecrets: true
    image: nisakoo/nexus-rate_limiter
    port: 8080
    database:
      enabled: false
    redis:
      enabled: true
    resources:
      limits:
        memory: "256Mi"
        cpu: "100m"

  authorization:
    enabled: true
    hasConfig: true
    hasSecrets: true
    image: nisakoo/nexus-authorization
    port: 8080
    database:
      enabled: false
    redis:
      enabled: true
    resources:
      limits:
        memory: "256Mi"
        cpu: "100m"
