apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-frontend-nginx
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        location / {
          root /var/www/public;
          index index.html;
          try_files $uri $uri/ /index.html;
        }
    }
