apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      name: http
  type: ClusterIP
