{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              name: http
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: static-files
              mountPath: /usr/share/nginx/html
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Chart.Name }}-frontend-nginx
        - name: static-files
          hostPath:
            path: {{ .Values.frontend.static }}
            type: Directory
{{- end }}
