{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/service.serversscheme: http
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
<<<<<<< HEAD
    - {{ .Values.ingress.host }}
    - {{ .Values.docs.host }}
    secretName: {{ .Chart.Name }}-tls-cert
  rules:
  - host: {{ .Values.docs.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}-docs-service
              port:
                name: http
  - host: {{ .Values.ingress.host }}
=======
    {{- range .Values.ingress.hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .Chart.Name }}-tls-cert
  rules:
  - host: clac-clac.ru
>>>>>>> fix/vk-oauth
    http:
      paths:
      - path: /api/events
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-realtime-service
            port:
              name: http
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-facade-service
            port:
              name: http
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-frontend-service
            port:
              name: http
  - host: clac-clac.mooo.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-frontend-service
            port:
              name: http
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-frontend-service
            port:
              name: http
{{- end }}
