{{- range $svcName, $svc := .Values.services }}
{{- if and $svc.enabled $svc.database.enabled }}

{{- $migrations := $.Files.Glob (printf "migrations/%s/*.sql" $svcName) }}
{{- if $migrations }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $svcName }}-migrations
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  {{- range $path, $bytes := $migrations }}
  {{ base $path }}: |-
{{ $bytes | toString | indent 4 }}
  {{- end }}
{{- end }}

{{- end }}
{{- end }}
---
{{- $initScript := .Files.Get "scripts/init_service_users.sql" }}
{{- if $initScript }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-init-scripts
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  init_service_users.sql: |-
{{ $initScript | indent 4 }}
{{- end }}
---
{{- $pgConf := .Files.Get "configs/postgresql.conf" }}
{{- if $pgConf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.namespace }}
data:
  postgresql.conf: |-
{{ $pgConf | indent 4 }}
{{- end }}
