{{- range $svcName, $svc := .Values.services }}
{{- if and $svc.enabled $svc.redis.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-{{ $svcName }}-redis-conf
  namespace: {{ $.Values.namespace }}
data:
  redis.conf: |
    requirepass $(REDIS_PASSWORD)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-{{ $svcName }}-redis
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $svcName }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $svcName }}-redis
  template:
    metadata:
      labels:
        app: {{ $svcName }}-redis
    spec:
      containers:
        - name: {{ $svcName }}
          image: {{ $.Values.redis.image }}
          args: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          ports:
            - containerPort: {{ $.Values.redis.port }}
              name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $svcName }}-secret
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-conf
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
          {{- with $.Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: redis-conf
          configMap:
            name: {{ $.Chart.Name }}-{{ $svcName }}-redis-conf
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ $svcName }}-redis-service
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $svcName }}-redis
  ports:
    - port: {{ $.Values.redis.port }}
      targetPort: redis
  type: ClusterIP
{{- end }}
{{- end }}
