{{- range $svcName, $svc := .Values.services }}
{{- if and $svc.enabled $svc.redis.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-{{ $svcName }}-redis
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $svcName }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $svcName }}-redis
  template:
    metadata:
      labels:
        app: {{ $svcName }}-redis
    spec:
      containers:
        - name: {{ $svcName }}
          image: {{ $.Values.redis.image }}
          ports:
            - containerPort: {{ $.Values.redis.port }}
              name: redis
          {{- with $.Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ $svcName }}-redis-service
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $svcName }}-redis
  ports:
    - port: {{ $.Values.redis.port }}
      targetPort: redis
  type: ClusterIP
{{- end }}
{{- end }}
