{{- range $svcName, $svc := .Values.services }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ $svcName }}-service
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $svcName }}
  ports:
    - port: {{ $svc.port }}
      targetPort: http
      name: http
  type: ClusterIP
{{- end }}
{{- end }}
