{{- range .Values.services }}
{{- if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ .name }}-service
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: {{ .port }}
      targetPort: http
      name: http
  type: ClusterIP
{{- end }}
{{- end }}
