COVERAGE_FILE=coverage.out
MIN_COVERAGE=70
# Автоматически собираем все пакеты из internal и исключаем моки
COVERPKG := $(shell go list ./... | grep -v /mock | paste -sd "," -)

.PHONY: unit unit-only-fail cover report ci

unit:
	@go test -v -race ./...

unit-only-fail:
	@go test -v ./... | grep "FAIL"

cover:
	@go test -count=1 -timeout=5m -race -coverpkg=$(COVERPKG) -coverprofile=$(COVERAGE_FILE) ./internal/...

report: cover
	@go tool cover -html=$(COVERAGE_FILE)

ci: cover
	@TOTAL_COVERAGE=$$(go tool cover -func=$(COVERAGE_FILE) | grep total | awk '{print $$3}' | tr -d '%'); \
	echo "Total coverage: $$TOTAL_COVERAGE%"; \
	if [ $$(echo "$$TOTAL_COVERAGE < $(MIN_COVERAGE)" | bc -l) -eq 1 ]; then \
		echo "FAILED: Coverage is below $(MIN_COVERAGE)%"; \
		exit 1; \
	fi
