// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/card/v1/card.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	ExecutorName  *string                `protobuf:"bytes,2,opt,name=executor_name,json=executorName,proto3,oneof" json:"executor_name,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	Subtasks      []*SubtaskInfo         `protobuf:"bytes,6,rep,name=subtasks,proto3" json:"subtasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardInfo) Reset() {
	*x = CardInfo{}
	mi := &file_proto_card_v1_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInfo) ProtoMessage() {}

func (x *CardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInfo.ProtoReflect.Descriptor instead.
func (*CardInfo) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{0}
}

func (x *CardInfo) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CardInfo) GetExecutorName() string {
	if x != nil && x.ExecutorName != nil {
		return *x.ExecutorName
	}
	return ""
}

func (x *CardInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CardInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CardInfo) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *CardInfo) GetSubtasks() []*SubtaskInfo {
	if x != nil {
		return x.Subtasks
	}
	return nil
}

type SubtaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubtaskLink   string                 `protobuf:"bytes,1,opt,name=subtask_link,json=subtaskLink,proto3" json:"subtask_link,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsDone        bool                   `protobuf:"varint,3,opt,name=isDone,proto3" json:"isDone,omitempty"`
	Position      int64                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtaskInfo) Reset() {
	*x = SubtaskInfo{}
	mi := &file_proto_card_v1_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtaskInfo) ProtoMessage() {}

func (x *SubtaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtaskInfo.ProtoReflect.Descriptor instead.
func (*SubtaskInfo) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{1}
}

func (x *SubtaskInfo) GetSubtaskLink() string {
	if x != nil {
		return x.SubtaskLink
	}
	return ""
}

func (x *SubtaskInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SubtaskInfo) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *SubtaskInfo) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

type CommentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentLink   string                 `protobuf:"bytes,1,opt,name=comment_link,json=commentLink,proto3" json:"comment_link,omitempty"`
	ParentLink    *string                `protobuf:"bytes,2,opt,name=parent_link,json=parentLink,proto3,oneof" json:"parent_link,omitempty"`
	AuthorLink    string                 `protobuf:"bytes,3,opt,name=author_link,json=authorLink,proto3" json:"author_link,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	mi := &file_proto_card_v1_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{2}
}

func (x *CommentInfo) GetCommentLink() string {
	if x != nil {
		return x.CommentLink
	}
	return ""
}

func (x *CommentInfo) GetParentLink() string {
	if x != nil && x.ParentLink != nil {
		return *x.ParentLink
	}
	return ""
}

func (x *CommentInfo) GetAuthorLink() string {
	if x != nil {
		return x.AuthorLink
	}
	return ""
}

func (x *CommentInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// GetCard
type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	CardLink      string                 `protobuf:"bytes,2,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{3}
}

func (x *GetCardRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *GetCardRequest) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

type GetCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardInfo      *CardInfo              `protobuf:"bytes,1,opt,name=card_info,json=cardInfo,proto3" json:"card_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{4}
}

func (x *GetCardResponse) GetCardInfo() *CardInfo {
	if x != nil {
		return x.CardInfo
	}
	return nil
}

// DeleteCard
type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	CardLink      string                 `protobuf:"bytes,2,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCardRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *DeleteCardRequest) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

type DeleteCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardResponse) Reset() {
	*x = DeleteCardResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardResponse) ProtoMessage() {}

func (x *DeleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{6}
}

// UpdateCard
type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	CardLink      string                 `protobuf:"bytes,2,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	ExecutorLink  *string                `protobuf:"bytes,3,opt,name=executor_link,json=executorLink,proto3,oneof" json:"executor_link,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCardRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *UpdateCardRequest) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

func (x *UpdateCardRequest) GetExecutorLink() string {
	if x != nil && x.ExecutorLink != nil {
		return *x.ExecutorLink
	}
	return ""
}

func (x *UpdateCardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCardRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type UpdateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardResponse) Reset() {
	*x = UpdateCardResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardResponse) ProtoMessage() {}

func (x *UpdateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardResponse.ProtoReflect.Descriptor instead.
func (*UpdateCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{8}
}

// ReorderCard
type ReorderCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	SectionLink   string                 `protobuf:"bytes,2,opt,name=section_link,json=sectionLink,proto3" json:"section_link,omitempty"`
	CardLink      string                 `protobuf:"bytes,3,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	Position      int64                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderCardsRequest) Reset() {
	*x = ReorderCardsRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderCardsRequest) ProtoMessage() {}

func (x *ReorderCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderCardsRequest.ProtoReflect.Descriptor instead.
func (*ReorderCardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{9}
}

func (x *ReorderCardsRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *ReorderCardsRequest) GetSectionLink() string {
	if x != nil {
		return x.SectionLink
	}
	return ""
}

func (x *ReorderCardsRequest) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

func (x *ReorderCardsRequest) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

type ReorderCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderCardsResponse) Reset() {
	*x = ReorderCardsResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderCardsResponse) ProtoMessage() {}

func (x *ReorderCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderCardsResponse.ProtoReflect.Descriptor instead.
func (*ReorderCardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{10}
}

// CreateCard
type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ExecutorLink  *string                `protobuf:"bytes,4,opt,name=executor_link,json=executorLink,proto3,oneof" json:"executor_link,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	SectionLink   string                 `protobuf:"bytes,6,opt,name=section_link,json=sectionLink,proto3" json:"section_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCardRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *CreateCardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCardRequest) GetExecutorLink() string {
	if x != nil && x.ExecutorLink != nil {
		return *x.ExecutorLink
	}
	return ""
}

func (x *CreateCardRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *CreateCardRequest) GetSectionLink() string {
	if x != nil {
		return x.SectionLink
	}
	return ""
}

type CreateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardLink      string                 `protobuf:"bytes,1,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	SectionLink   string                 `protobuf:"bytes,2,opt,name=section_link,json=sectionLink,proto3" json:"section_link,omitempty"`
	Position      int64                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{12}
}

func (x *CreateCardResponse) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

func (x *CreateCardResponse) GetSectionLink() string {
	if x != nil {
		return x.SectionLink
	}
	return ""
}

func (x *CreateCardResponse) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

// GetComments
type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	CardLink      string                 `protobuf:"bytes,2,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{13}
}

func (x *GetCommentsRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *GetCommentsRequest) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentsInfo  []*CommentInfo         `protobuf:"bytes,1,rep,name=comments_info,json=commentsInfo,proto3" json:"comments_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{14}
}

func (x *GetCommentsResponse) GetCommentsInfo() []*CommentInfo {
	if x != nil {
		return x.CommentsInfo
	}
	return nil
}

// CreateComment
type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	CardLink      string                 `protobuf:"bytes,2,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	ParentLink    *string                `protobuf:"bytes,3,opt,name=parent_link,json=parentLink,proto3,oneof" json:"parent_link,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCommentRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *CreateCommentRequest) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

func (x *CreateCommentRequest) GetParentLink() string {
	if x != nil && x.ParentLink != nil {
		return *x.ParentLink
	}
	return ""
}

func (x *CreateCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentLink   string                 `protobuf:"bytes,1,opt,name=comment_link,json=commentLink,proto3" json:"comment_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCommentResponse) GetCommentLink() string {
	if x != nil {
		return x.CommentLink
	}
	return ""
}

// DeleteComment
type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentLink   string                 `protobuf:"bytes,1,opt,name=comment_link,json=commentLink,proto3" json:"comment_link,omitempty"`
	UserLink      string                 `protobuf:"bytes,2,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteCommentRequest) GetCommentLink() string {
	if x != nil {
		return x.CommentLink
	}
	return ""
}

func (x *DeleteCommentRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{18}
}

// UpdateComment
type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentLink   string                 `protobuf:"bytes,1,opt,name=comment_link,json=commentLink,proto3" json:"comment_link,omitempty"`
	UserLink      string                 `protobuf:"bytes,2,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateCommentRequest) GetCommentLink() string {
	if x != nil {
		return x.CommentLink
	}
	return ""
}

func (x *UpdateCommentRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *UpdateCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UpdateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentResponse) Reset() {
	*x = UpdateCommentResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentResponse) ProtoMessage() {}

func (x *UpdateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{20}
}

type CreateSubtaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	CardLink      string                 `protobuf:"bytes,2,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubtaskRequest) Reset() {
	*x = CreateSubtaskRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubtaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubtaskRequest) ProtoMessage() {}

func (x *CreateSubtaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubtaskRequest.ProtoReflect.Descriptor instead.
func (*CreateSubtaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{21}
}

func (x *CreateSubtaskRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *CreateSubtaskRequest) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

func (x *CreateSubtaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateSubtaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubtaskLink   string                 `protobuf:"bytes,1,opt,name=subtask_link,json=subtaskLink,proto3" json:"subtask_link,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsDone        bool                   `protobuf:"varint,3,opt,name=isDone,proto3" json:"isDone,omitempty"`
	Position      int64                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubtaskResponse) Reset() {
	*x = CreateSubtaskResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubtaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubtaskResponse) ProtoMessage() {}

func (x *CreateSubtaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubtaskResponse.ProtoReflect.Descriptor instead.
func (*CreateSubtaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{22}
}

func (x *CreateSubtaskResponse) GetSubtaskLink() string {
	if x != nil {
		return x.SubtaskLink
	}
	return ""
}

func (x *CreateSubtaskResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSubtaskResponse) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *CreateSubtaskResponse) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

type UpdateSubtaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	SubtaskLink   string                 `protobuf:"bytes,2,opt,name=subtask_link,json=subtaskLink,proto3" json:"subtask_link,omitempty"`
	IsDone        bool                   `protobuf:"varint,3,opt,name=is_done,json=isDone,proto3" json:"is_done,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubtaskRequest) Reset() {
	*x = UpdateSubtaskRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubtaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubtaskRequest) ProtoMessage() {}

func (x *UpdateSubtaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubtaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubtaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateSubtaskRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *UpdateSubtaskRequest) GetSubtaskLink() string {
	if x != nil {
		return x.SubtaskLink
	}
	return ""
}

func (x *UpdateSubtaskRequest) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *UpdateSubtaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateSubtaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubtaskResponse) Reset() {
	*x = UpdateSubtaskResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubtaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubtaskResponse) ProtoMessage() {}

func (x *UpdateSubtaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubtaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateSubtaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{24}
}

type DeleteSubtaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	SubtaskLink   string                 `protobuf:"bytes,2,opt,name=subtask_link,json=subtaskLink,proto3" json:"subtask_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubtaskRequest) Reset() {
	*x = DeleteSubtaskRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubtaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubtaskRequest) ProtoMessage() {}

func (x *DeleteSubtaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubtaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubtaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteSubtaskRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *DeleteSubtaskRequest) GetSubtaskLink() string {
	if x != nil {
		return x.SubtaskLink
	}
	return ""
}

type DeleteSubtaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubtaskResponse) Reset() {
	*x = DeleteSubtaskResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubtaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubtaskResponse) ProtoMessage() {}

func (x *DeleteSubtaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubtaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubtaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{26}
}

var File_proto_card_v1_card_proto protoreflect.FileDescriptor

const file_proto_card_v1_card_proto_rawDesc = "" +
	"\n" +
	"\x18proto/card/v1/card.proto\x12\rproto.card.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x02\n" +
	"\bCardInfo\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12(\n" +
	"\rexecutor_name\x18\x02 \x01(\tH\x00R\fexecutorName\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12;\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bdeadline\x88\x01\x01\x126\n" +
	"\bsubtasks\x18\x06 \x03(\v2\x1a.proto.card.v1.SubtaskInfoR\bsubtasksB\x10\n" +
	"\x0e_executor_nameB\v\n" +
	"\t_deadline\"\x86\x01\n" +
	"\vSubtaskInfo\x12!\n" +
	"\fsubtask_link\x18\x01 \x01(\tR\vsubtaskLink\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06isDone\x18\x03 \x01(\bR\x06isDone\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x03R\bposition\"\x9b\x01\n" +
	"\vCommentInfo\x12!\n" +
	"\fcomment_link\x18\x01 \x01(\tR\vcommentLink\x12$\n" +
	"\vparent_link\x18\x02 \x01(\tH\x00R\n" +
	"parentLink\x88\x01\x01\x12\x1f\n" +
	"\vauthor_link\x18\x03 \x01(\tR\n" +
	"authorLink\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04textB\x0e\n" +
	"\f_parent_link\"J\n" +
	"\x0eGetCardRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x1b\n" +
	"\tcard_link\x18\x02 \x01(\tR\bcardLink\"G\n" +
	"\x0fGetCardResponse\x124\n" +
	"\tcard_info\x18\x01 \x01(\v2\x17.proto.card.v1.CardInfoR\bcardInfo\"M\n" +
	"\x11DeleteCardRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x1b\n" +
	"\tcard_link\x18\x02 \x01(\tR\bcardLink\"\x14\n" +
	"\x12DeleteCardResponse\"\x8b\x02\n" +
	"\x11UpdateCardRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x1b\n" +
	"\tcard_link\x18\x02 \x01(\tR\bcardLink\x12(\n" +
	"\rexecutor_link\x18\x03 \x01(\tH\x00R\fexecutorLink\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12;\n" +
	"\bdeadline\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bdeadline\x88\x01\x01B\x10\n" +
	"\x0e_executor_linkB\v\n" +
	"\t_deadline\"\x14\n" +
	"\x12UpdateCardResponse\"\x8e\x01\n" +
	"\x13ReorderCardsRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12!\n" +
	"\fsection_link\x18\x02 \x01(\tR\vsectionLink\x12\x1b\n" +
	"\tcard_link\x18\x03 \x01(\tR\bcardLink\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x03R\bposition\"\x16\n" +
	"\x14ReorderCardsResponse\"\x91\x02\n" +
	"\x11CreateCardRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12(\n" +
	"\rexecutor_link\x18\x04 \x01(\tH\x00R\fexecutorLink\x88\x01\x01\x12;\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bdeadline\x88\x01\x01\x12!\n" +
	"\fsection_link\x18\x06 \x01(\tR\vsectionLinkB\x10\n" +
	"\x0e_executor_linkB\v\n" +
	"\t_deadline\"p\n" +
	"\x12CreateCardResponse\x12\x1b\n" +
	"\tcard_link\x18\x01 \x01(\tR\bcardLink\x12!\n" +
	"\fsection_link\x18\x02 \x01(\tR\vsectionLink\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x03R\bposition\"N\n" +
	"\x12GetCommentsRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x1b\n" +
	"\tcard_link\x18\x02 \x01(\tR\bcardLink\"V\n" +
	"\x13GetCommentsResponse\x12?\n" +
	"\rcomments_info\x18\x01 \x03(\v2\x1a.proto.card.v1.CommentInfoR\fcommentsInfo\"\x9a\x01\n" +
	"\x14CreateCommentRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x1b\n" +
	"\tcard_link\x18\x02 \x01(\tR\bcardLink\x12$\n" +
	"\vparent_link\x18\x03 \x01(\tH\x00R\n" +
	"parentLink\x88\x01\x01\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04textB\x0e\n" +
	"\f_parent_link\":\n" +
	"\x15CreateCommentResponse\x12!\n" +
	"\fcomment_link\x18\x01 \x01(\tR\vcommentLink\"V\n" +
	"\x14DeleteCommentRequest\x12!\n" +
	"\fcomment_link\x18\x01 \x01(\tR\vcommentLink\x12\x1b\n" +
	"\tuser_link\x18\x02 \x01(\tR\buserLink\"\x17\n" +
	"\x15DeleteCommentResponse\"j\n" +
	"\x14UpdateCommentRequest\x12!\n" +
	"\fcomment_link\x18\x01 \x01(\tR\vcommentLink\x12\x1b\n" +
	"\tuser_link\x18\x02 \x01(\tR\buserLink\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x17\n" +
	"\x15UpdateCommentResponse\"r\n" +
	"\x14CreateSubtaskRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x1b\n" +
	"\tcard_link\x18\x02 \x01(\tR\bcardLink\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x90\x01\n" +
	"\x15CreateSubtaskResponse\x12!\n" +
	"\fsubtask_link\x18\x01 \x01(\tR\vsubtaskLink\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06isDone\x18\x03 \x01(\bR\x06isDone\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x03R\bposition\"\x91\x01\n" +
	"\x14UpdateSubtaskRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12!\n" +
	"\fsubtask_link\x18\x02 \x01(\tR\vsubtaskLink\x12\x17\n" +
	"\ais_done\x18\x03 \x01(\bR\x06isDone\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x17\n" +
	"\x15UpdateSubtaskResponse\"V\n" +
	"\x14DeleteSubtaskRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12!\n" +
	"\fsubtask_link\x18\x02 \x01(\tR\vsubtaskLink\"\x17\n" +
	"\x15DeleteSubtaskResponse2\xa7\b\n" +
	"\vCardService\x12H\n" +
	"\aGetCard\x12\x1d.proto.card.v1.GetCardRequest\x1a\x1e.proto.card.v1.GetCardResponse\x12Q\n" +
	"\n" +
	"DeleteCard\x12 .proto.card.v1.DeleteCardRequest\x1a!.proto.card.v1.DeleteCardResponse\x12Q\n" +
	"\n" +
	"UpdateCard\x12 .proto.card.v1.UpdateCardRequest\x1a!.proto.card.v1.UpdateCardResponse\x12W\n" +
	"\fReorderCards\x12\".proto.card.v1.ReorderCardsRequest\x1a#.proto.card.v1.ReorderCardsResponse\x12Q\n" +
	"\n" +
	"CreateCard\x12 .proto.card.v1.CreateCardRequest\x1a!.proto.card.v1.CreateCardResponse\x12T\n" +
	"\vGetComments\x12!.proto.card.v1.GetCommentsRequest\x1a\".proto.card.v1.GetCommentsResponse\x12Z\n" +
	"\rCreateComment\x12#.proto.card.v1.CreateCommentRequest\x1a$.proto.card.v1.CreateCommentResponse\x12Z\n" +
	"\rDeleteComment\x12#.proto.card.v1.DeleteCommentRequest\x1a$.proto.card.v1.DeleteCommentResponse\x12Z\n" +
	"\rUpdateComment\x12#.proto.card.v1.UpdateCommentRequest\x1a$.proto.card.v1.UpdateCommentResponse\x12Z\n" +
	"\rCreateSubtask\x12#.proto.card.v1.CreateSubtaskRequest\x1a$.proto.card.v1.CreateSubtaskResponse\x12Z\n" +
	"\rUpdateSubtask\x12#.proto.card.v1.UpdateSubtaskRequest\x1a$.proto.card.v1.UpdateSubtaskResponse\x12Z\n" +
	"\rDeleteSubtask\x12#.proto.card.v1.DeleteSubtaskRequest\x1a$.proto.card.v1.DeleteSubtaskResponseB?Z=github.com/go-park-mail-ru/2026_1_Clac_Clac/pkg/proto/card/v1b\x06proto3"

var (
	file_proto_card_v1_card_proto_rawDescOnce sync.Once
	file_proto_card_v1_card_proto_rawDescData []byte
)

func file_proto_card_v1_card_proto_rawDescGZIP() []byte {
	file_proto_card_v1_card_proto_rawDescOnce.Do(func() {
		file_proto_card_v1_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_card_v1_card_proto_rawDesc), len(file_proto_card_v1_card_proto_rawDesc)))
	})
	return file_proto_card_v1_card_proto_rawDescData
}

var file_proto_card_v1_card_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_card_v1_card_proto_goTypes = []any{
	(*CardInfo)(nil),              // 0: proto.card.v1.CardInfo
	(*SubtaskInfo)(nil),           // 1: proto.card.v1.SubtaskInfo
	(*CommentInfo)(nil),           // 2: proto.card.v1.CommentInfo
	(*GetCardRequest)(nil),        // 3: proto.card.v1.GetCardRequest
	(*GetCardResponse)(nil),       // 4: proto.card.v1.GetCardResponse
	(*DeleteCardRequest)(nil),     // 5: proto.card.v1.DeleteCardRequest
	(*DeleteCardResponse)(nil),    // 6: proto.card.v1.DeleteCardResponse
	(*UpdateCardRequest)(nil),     // 7: proto.card.v1.UpdateCardRequest
	(*UpdateCardResponse)(nil),    // 8: proto.card.v1.UpdateCardResponse
	(*ReorderCardsRequest)(nil),   // 9: proto.card.v1.ReorderCardsRequest
	(*ReorderCardsResponse)(nil),  // 10: proto.card.v1.ReorderCardsResponse
	(*CreateCardRequest)(nil),     // 11: proto.card.v1.CreateCardRequest
	(*CreateCardResponse)(nil),    // 12: proto.card.v1.CreateCardResponse
	(*GetCommentsRequest)(nil),    // 13: proto.card.v1.GetCommentsRequest
	(*GetCommentsResponse)(nil),   // 14: proto.card.v1.GetCommentsResponse
	(*CreateCommentRequest)(nil),  // 15: proto.card.v1.CreateCommentRequest
	(*CreateCommentResponse)(nil), // 16: proto.card.v1.CreateCommentResponse
	(*DeleteCommentRequest)(nil),  // 17: proto.card.v1.DeleteCommentRequest
	(*DeleteCommentResponse)(nil), // 18: proto.card.v1.DeleteCommentResponse
	(*UpdateCommentRequest)(nil),  // 19: proto.card.v1.UpdateCommentRequest
	(*UpdateCommentResponse)(nil), // 20: proto.card.v1.UpdateCommentResponse
	(*CreateSubtaskRequest)(nil),  // 21: proto.card.v1.CreateSubtaskRequest
	(*CreateSubtaskResponse)(nil), // 22: proto.card.v1.CreateSubtaskResponse
	(*UpdateSubtaskRequest)(nil),  // 23: proto.card.v1.UpdateSubtaskRequest
	(*UpdateSubtaskResponse)(nil), // 24: proto.card.v1.UpdateSubtaskResponse
	(*DeleteSubtaskRequest)(nil),  // 25: proto.card.v1.DeleteSubtaskRequest
	(*DeleteSubtaskResponse)(nil), // 26: proto.card.v1.DeleteSubtaskResponse
	(*timestamppb.Timestamp)(nil), // 27: google.protobuf.Timestamp
}
var file_proto_card_v1_card_proto_depIdxs = []int32{
	27, // 0: proto.card.v1.CardInfo.deadline:type_name -> google.protobuf.Timestamp
	1,  // 1: proto.card.v1.CardInfo.subtasks:type_name -> proto.card.v1.SubtaskInfo
	0,  // 2: proto.card.v1.GetCardResponse.card_info:type_name -> proto.card.v1.CardInfo
	27, // 3: proto.card.v1.UpdateCardRequest.deadline:type_name -> google.protobuf.Timestamp
	27, // 4: proto.card.v1.CreateCardRequest.deadline:type_name -> google.protobuf.Timestamp
	2,  // 5: proto.card.v1.GetCommentsResponse.comments_info:type_name -> proto.card.v1.CommentInfo
	3,  // 6: proto.card.v1.CardService.GetCard:input_type -> proto.card.v1.GetCardRequest
	5,  // 7: proto.card.v1.CardService.DeleteCard:input_type -> proto.card.v1.DeleteCardRequest
	7,  // 8: proto.card.v1.CardService.UpdateCard:input_type -> proto.card.v1.UpdateCardRequest
	9,  // 9: proto.card.v1.CardService.ReorderCards:input_type -> proto.card.v1.ReorderCardsRequest
	11, // 10: proto.card.v1.CardService.CreateCard:input_type -> proto.card.v1.CreateCardRequest
	13, // 11: proto.card.v1.CardService.GetComments:input_type -> proto.card.v1.GetCommentsRequest
	15, // 12: proto.card.v1.CardService.CreateComment:input_type -> proto.card.v1.CreateCommentRequest
	17, // 13: proto.card.v1.CardService.DeleteComment:input_type -> proto.card.v1.DeleteCommentRequest
	19, // 14: proto.card.v1.CardService.UpdateComment:input_type -> proto.card.v1.UpdateCommentRequest
	21, // 15: proto.card.v1.CardService.CreateSubtask:input_type -> proto.card.v1.CreateSubtaskRequest
	23, // 16: proto.card.v1.CardService.UpdateSubtask:input_type -> proto.card.v1.UpdateSubtaskRequest
	25, // 17: proto.card.v1.CardService.DeleteSubtask:input_type -> proto.card.v1.DeleteSubtaskRequest
	4,  // 18: proto.card.v1.CardService.GetCard:output_type -> proto.card.v1.GetCardResponse
	6,  // 19: proto.card.v1.CardService.DeleteCard:output_type -> proto.card.v1.DeleteCardResponse
	8,  // 20: proto.card.v1.CardService.UpdateCard:output_type -> proto.card.v1.UpdateCardResponse
	10, // 21: proto.card.v1.CardService.ReorderCards:output_type -> proto.card.v1.ReorderCardsResponse
	12, // 22: proto.card.v1.CardService.CreateCard:output_type -> proto.card.v1.CreateCardResponse
	14, // 23: proto.card.v1.CardService.GetComments:output_type -> proto.card.v1.GetCommentsResponse
	16, // 24: proto.card.v1.CardService.CreateComment:output_type -> proto.card.v1.CreateCommentResponse
	18, // 25: proto.card.v1.CardService.DeleteComment:output_type -> proto.card.v1.DeleteCommentResponse
	20, // 26: proto.card.v1.CardService.UpdateComment:output_type -> proto.card.v1.UpdateCommentResponse
	22, // 27: proto.card.v1.CardService.CreateSubtask:output_type -> proto.card.v1.CreateSubtaskResponse
	24, // 28: proto.card.v1.CardService.UpdateSubtask:output_type -> proto.card.v1.UpdateSubtaskResponse
	26, // 29: proto.card.v1.CardService.DeleteSubtask:output_type -> proto.card.v1.DeleteSubtaskResponse
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_card_v1_card_proto_init() }
func file_proto_card_v1_card_proto_init() {
	if File_proto_card_v1_card_proto != nil {
		return
	}
	file_proto_card_v1_card_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_card_v1_card_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_card_v1_card_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_card_v1_card_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_card_v1_card_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_card_v1_card_proto_rawDesc), len(file_proto_card_v1_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_card_v1_card_proto_goTypes,
		DependencyIndexes: file_proto_card_v1_card_proto_depIdxs,
		MessageInfos:      file_proto_card_v1_card_proto_msgTypes,
	}.Build()
	File_proto_card_v1_card_proto = out.File
	file_proto_card_v1_card_proto_goTypes = nil
	file_proto_card_v1_card_proto_depIdxs = nil
}
