// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/card/v1/card.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	ExecuterName  *string                `protobuf:"bytes,2,opt,name=executer_name,json=executerName,proto3,oneof" json:"executer_name,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardInfo) Reset() {
	*x = CardInfo{}
	mi := &file_proto_card_v1_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInfo) ProtoMessage() {}

func (x *CardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInfo.ProtoReflect.Descriptor instead.
func (*CardInfo) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{0}
}

func (x *CardInfo) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CardInfo) GetExecuterName() string {
	if x != nil && x.ExecuterName != nil {
		return *x.ExecuterName
	}
	return ""
}

func (x *CardInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CardInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CardInfo) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

// GetCard
type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardLink      string                 `protobuf:"bytes,1,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{1}
}

func (x *GetCardRequest) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

type GetCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardInfo      *CardInfo              `protobuf:"bytes,1,opt,name=card_info,json=cardInfo,proto3" json:"card_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{2}
}

func (x *GetCardResponse) GetCardInfo() *CardInfo {
	if x != nil {
		return x.CardInfo
	}
	return nil
}

// DeleteCard
type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardLink      string                 `protobuf:"bytes,1,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCardRequest) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

type DeleteCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardResponse) Reset() {
	*x = DeleteCardResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardResponse) ProtoMessage() {}

func (x *DeleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{4}
}

// UpdateCard
type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardLink      string                 `protobuf:"bytes,1,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	ExecutorLink  *string                `protobuf:"bytes,2,opt,name=executor_link,json=executorLink,proto3,oneof" json:"executor_link,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCardRequest) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

func (x *UpdateCardRequest) GetExecutorLink() string {
	if x != nil && x.ExecutorLink != nil {
		return *x.ExecutorLink
	}
	return ""
}

func (x *UpdateCardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCardRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type UpdateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardResponse) Reset() {
	*x = UpdateCardResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardResponse) ProtoMessage() {}

func (x *UpdateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardResponse.ProtoReflect.Descriptor instead.
func (*UpdateCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{6}
}

// ReorderCard
type ReorderCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionLink   string                 `protobuf:"bytes,1,opt,name=section_link,json=sectionLink,proto3" json:"section_link,omitempty"`
	CardLink      string                 `protobuf:"bytes,2,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	Position      int64                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderCardsRequest) Reset() {
	*x = ReorderCardsRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderCardsRequest) ProtoMessage() {}

func (x *ReorderCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderCardsRequest.ProtoReflect.Descriptor instead.
func (*ReorderCardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{7}
}

func (x *ReorderCardsRequest) GetSectionLink() string {
	if x != nil {
		return x.SectionLink
	}
	return ""
}

func (x *ReorderCardsRequest) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

func (x *ReorderCardsRequest) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

type ReorderCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderCardsResponse) Reset() {
	*x = ReorderCardsResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderCardsResponse) ProtoMessage() {}

func (x *ReorderCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderCardsResponse.ProtoReflect.Descriptor instead.
func (*ReorderCardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{8}
}

// CreateCard
type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorLink    string                 `protobuf:"bytes,1,opt,name=author_link,json=authorLink,proto3" json:"author_link,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ExecutorLink  *string                `protobuf:"bytes,4,opt,name=executor_link,json=executorLink,proto3,oneof" json:"executor_link,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	SectionLink   string                 `protobuf:"bytes,6,opt,name=section_link,json=sectionLink,proto3" json:"section_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_proto_card_v1_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCardRequest) GetAuthorLink() string {
	if x != nil {
		return x.AuthorLink
	}
	return ""
}

func (x *CreateCardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCardRequest) GetExecutorLink() string {
	if x != nil && x.ExecutorLink != nil {
		return *x.ExecutorLink
	}
	return ""
}

func (x *CreateCardRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *CreateCardRequest) GetSectionLink() string {
	if x != nil {
		return x.SectionLink
	}
	return ""
}

type CreateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardLink      string                 `protobuf:"bytes,1,opt,name=card_link,json=cardLink,proto3" json:"card_link,omitempty"`
	SectionLink   string                 `protobuf:"bytes,2,opt,name=section_link,json=sectionLink,proto3" json:"section_link,omitempty"`
	Position      int64                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_proto_card_v1_card_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_v1_card_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_card_v1_card_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCardResponse) GetCardLink() string {
	if x != nil {
		return x.CardLink
	}
	return ""
}

func (x *CreateCardResponse) GetSectionLink() string {
	if x != nil {
		return x.SectionLink
	}
	return ""
}

func (x *CreateCardResponse) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

var File_proto_card_v1_card_proto protoreflect.FileDescriptor

const file_proto_card_v1_card_proto_rawDesc = "" +
	"\n" +
	"\x18proto/card/v1/card.proto\x12\rproto.card.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x01\n" +
	"\bCardInfo\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12(\n" +
	"\rexecuter_name\x18\x02 \x01(\tH\x00R\fexecuterName\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12;\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bdeadline\x88\x01\x01B\x10\n" +
	"\x0e_executer_nameB\v\n" +
	"\t_deadline\"-\n" +
	"\x0eGetCardRequest\x12\x1b\n" +
	"\tcard_link\x18\x01 \x01(\tR\bcardLink\"G\n" +
	"\x0fGetCardResponse\x124\n" +
	"\tcard_info\x18\x01 \x01(\v2\x17.proto.card.v1.CardInfoR\bcardInfo\"0\n" +
	"\x11DeleteCardRequest\x12\x1b\n" +
	"\tcard_link\x18\x01 \x01(\tR\bcardLink\"\x14\n" +
	"\x12DeleteCardResponse\"\xee\x01\n" +
	"\x11UpdateCardRequest\x12\x1b\n" +
	"\tcard_link\x18\x01 \x01(\tR\bcardLink\x12(\n" +
	"\rexecutor_link\x18\x02 \x01(\tH\x00R\fexecutorLink\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12;\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bdeadline\x88\x01\x01B\x10\n" +
	"\x0e_executor_linkB\v\n" +
	"\t_deadline\"\x14\n" +
	"\x12UpdateCardResponse\"q\n" +
	"\x13ReorderCardsRequest\x12!\n" +
	"\fsection_link\x18\x01 \x01(\tR\vsectionLink\x12\x1b\n" +
	"\tcard_link\x18\x02 \x01(\tR\bcardLink\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x03R\bposition\"\x16\n" +
	"\x14ReorderCardsResponse\"\x95\x02\n" +
	"\x11CreateCardRequest\x12\x1f\n" +
	"\vauthor_link\x18\x01 \x01(\tR\n" +
	"authorLink\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12(\n" +
	"\rexecutor_link\x18\x04 \x01(\tH\x00R\fexecutorLink\x88\x01\x01\x12;\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bdeadline\x88\x01\x01\x12!\n" +
	"\fsection_link\x18\x06 \x01(\tR\vsectionLinkB\x10\n" +
	"\x0e_executor_linkB\v\n" +
	"\t_deadline\"p\n" +
	"\x12CreateCardResponse\x12\x1b\n" +
	"\tcard_link\x18\x01 \x01(\tR\bcardLink\x12!\n" +
	"\fsection_link\x18\x02 \x01(\tR\vsectionLink\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x03R\bposition2\xa9\x03\n" +
	"\vCardService\x12H\n" +
	"\aGetCard\x12\x1d.proto.card.v1.GetCardRequest\x1a\x1e.proto.card.v1.GetCardResponse\x12Q\n" +
	"\n" +
	"DeleteCard\x12 .proto.card.v1.DeleteCardRequest\x1a!.proto.card.v1.DeleteCardResponse\x12Q\n" +
	"\n" +
	"UpdateCard\x12 .proto.card.v1.UpdateCardRequest\x1a!.proto.card.v1.UpdateCardResponse\x12W\n" +
	"\fReorderCards\x12\".proto.card.v1.ReorderCardsRequest\x1a#.proto.card.v1.ReorderCardsResponse\x12Q\n" +
	"\n" +
	"CreateCard\x12 .proto.card.v1.CreateCardRequest\x1a!.proto.card.v1.CreateCardResponseB?Z=github.com/go-park-mail-ru/2026_1_Clac_Clac/pkg/proto/card/v1b\x06proto3"

var (
	file_proto_card_v1_card_proto_rawDescOnce sync.Once
	file_proto_card_v1_card_proto_rawDescData []byte
)

func file_proto_card_v1_card_proto_rawDescGZIP() []byte {
	file_proto_card_v1_card_proto_rawDescOnce.Do(func() {
		file_proto_card_v1_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_card_v1_card_proto_rawDesc), len(file_proto_card_v1_card_proto_rawDesc)))
	})
	return file_proto_card_v1_card_proto_rawDescData
}

var file_proto_card_v1_card_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_card_v1_card_proto_goTypes = []any{
	(*CardInfo)(nil),              // 0: proto.card.v1.CardInfo
	(*GetCardRequest)(nil),        // 1: proto.card.v1.GetCardRequest
	(*GetCardResponse)(nil),       // 2: proto.card.v1.GetCardResponse
	(*DeleteCardRequest)(nil),     // 3: proto.card.v1.DeleteCardRequest
	(*DeleteCardResponse)(nil),    // 4: proto.card.v1.DeleteCardResponse
	(*UpdateCardRequest)(nil),     // 5: proto.card.v1.UpdateCardRequest
	(*UpdateCardResponse)(nil),    // 6: proto.card.v1.UpdateCardResponse
	(*ReorderCardsRequest)(nil),   // 7: proto.card.v1.ReorderCardsRequest
	(*ReorderCardsResponse)(nil),  // 8: proto.card.v1.ReorderCardsResponse
	(*CreateCardRequest)(nil),     // 9: proto.card.v1.CreateCardRequest
	(*CreateCardResponse)(nil),    // 10: proto.card.v1.CreateCardResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_proto_card_v1_card_proto_depIdxs = []int32{
	11, // 0: proto.card.v1.CardInfo.deadline:type_name -> google.protobuf.Timestamp
	0,  // 1: proto.card.v1.GetCardResponse.card_info:type_name -> proto.card.v1.CardInfo
	11, // 2: proto.card.v1.UpdateCardRequest.deadline:type_name -> google.protobuf.Timestamp
	11, // 3: proto.card.v1.CreateCardRequest.deadline:type_name -> google.protobuf.Timestamp
	1,  // 4: proto.card.v1.CardService.GetCard:input_type -> proto.card.v1.GetCardRequest
	3,  // 5: proto.card.v1.CardService.DeleteCard:input_type -> proto.card.v1.DeleteCardRequest
	5,  // 6: proto.card.v1.CardService.UpdateCard:input_type -> proto.card.v1.UpdateCardRequest
	7,  // 7: proto.card.v1.CardService.ReorderCards:input_type -> proto.card.v1.ReorderCardsRequest
	9,  // 8: proto.card.v1.CardService.CreateCard:input_type -> proto.card.v1.CreateCardRequest
	2,  // 9: proto.card.v1.CardService.GetCard:output_type -> proto.card.v1.GetCardResponse
	4,  // 10: proto.card.v1.CardService.DeleteCard:output_type -> proto.card.v1.DeleteCardResponse
	6,  // 11: proto.card.v1.CardService.UpdateCard:output_type -> proto.card.v1.UpdateCardResponse
	8,  // 12: proto.card.v1.CardService.ReorderCards:output_type -> proto.card.v1.ReorderCardsResponse
	10, // 13: proto.card.v1.CardService.CreateCard:output_type -> proto.card.v1.CreateCardResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_card_v1_card_proto_init() }
func file_proto_card_v1_card_proto_init() {
	if File_proto_card_v1_card_proto != nil {
		return
	}
	file_proto_card_v1_card_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_card_v1_card_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_card_v1_card_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_card_v1_card_proto_rawDesc), len(file_proto_card_v1_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_card_v1_card_proto_goTypes,
		DependencyIndexes: file_proto_card_v1_card_proto_depIdxs,
		MessageInfos:      file_proto_card_v1_card_proto_msgTypes,
	}.Build()
	File_proto_card_v1_card_proto = out.File
	file_proto_card_v1_card_proto_goTypes = nil
	file_proto_card_v1_card_proto_depIdxs = nil
}
