// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockCoolDownUC

import (
	context "context"

	domain "github.com/go-park-mail-ru/2026_1_Clac_Clac/facade/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// CoolDownUseCase is an autogenerated mock type for the CoolDownUseCase type
type CoolDownUseCase struct {
	mock.Mock
}

// CheckCoolDown provides a mock function with given fields: ctx, cooldown
func (_m *CoolDownUseCase) CheckCoolDown(ctx context.Context, cooldown domain.Cooldown) (domain.CooldownResult, error) {
	ret := _m.Called(ctx, cooldown)

	if len(ret) == 0 {
		panic("no return value specified for CheckCoolDown")
	}

	var r0 domain.CooldownResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Cooldown) (domain.CooldownResult, error)); ok {
		return rf(ctx, cooldown)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Cooldown) domain.CooldownResult); ok {
		r0 = rf(ctx, cooldown)
	} else {
		r0 = ret.Get(0).(domain.CooldownResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Cooldown) error); ok {
		r1 = rf(ctx, cooldown)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCoolDownUseCase creates a new instance of CoolDownUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoolDownUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoolDownUseCase {
	mock := &CoolDownUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
