// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/go-park-mail-ru/2026_1_Clac_Clac/internal/auth/service/dto"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// CheckCSRFToken provides a mock function with given fields: ctx, sessionId, token
func (_m *AuthService) CheckCSRFToken(ctx context.Context, sessionId string, token string) error {
	ret := _m.Called(ctx, sessionId, token)

	if len(ret) == 0 {
		panic("no return value specified for CheckCSRFToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sessionId, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckCoolDown provides a mock function with given fields: ctx, config
func (_m *AuthService) CheckCoolDown(ctx context.Context, config dto.CoolDownConfig) (bool, time.Duration, error) {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for CheckCoolDown")
	}

	var r0 bool
	var r1 time.Duration
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CoolDownConfig) (bool, time.Duration, error)); ok {
		return rf(ctx, config)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CoolDownConfig) bool); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CoolDownConfig) time.Duration); ok {
		r1 = rf(ctx, config)
	} else {
		r1 = ret.Get(1).(time.Duration)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.CoolDownConfig) error); ok {
		r2 = rf(ctx, config)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CheckRecoveryCode provides a mock function with given fields: ctx, tokenID
func (_m *AuthService) CheckRecoveryCode(ctx context.Context, tokenID string) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for CheckRecoveryCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSessionForUser provides a mock function with given fields: ctx, link
func (_m *AuthService) CreateSessionForUser(ctx context.Context, link uuid.UUID) (string, error) {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for CreateSessionForUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, link)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, link)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnsureUserByEmail provides a mock function with given fields: ctx, info
func (_m *AuthService) EnsureUserByEmail(ctx context.Context, info dto.RegistrationUser) (dto.UserInfo, error) {
	ret := _m.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for EnsureUserByEmail")
	}

	var r0 dto.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegistrationUser) (dto.UserInfo, error)); ok {
		return rf(ctx, info)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegistrationUser) dto.UserInfo); ok {
		r0 = rf(ctx, info)
	} else {
		r0 = ret.Get(0).(dto.UserInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RegistrationUser) error); ok {
		r1 = rf(ctx, info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateCSRFToken provides a mock function with given fields: ctx, sessionId, expireTime
func (_m *AuthService) GenerateCSRFToken(ctx context.Context, sessionId string, expireTime int64) (string, error) {
	ret := _m.Called(ctx, sessionId, expireTime)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCSRFToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (string, error)); ok {
		return rf(ctx, sessionId, expireTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) string); ok {
		r0 = rf(ctx, sessionId, expireTime)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, sessionId, expireTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCSRFTokenExpireTime provides a mock function with given fields: ctx
func (_m *AuthService) GetCSRFTokenExpireTime(ctx context.Context) (time.Time, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCSRFTokenExpireTime")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (time.Time, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) time.Time); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *AuthService) GetUserByEmail(ctx context.Context, email string) (dto.UserInfo, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 dto.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dto.UserInfo, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dto.UserInfo); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(dto.UserInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserLink provides a mock function with given fields: ctx, sessionID
func (_m *AuthService) GetUserLink(ctx context.Context, sessionID string) (uuid.UUID, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLink")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogIn provides a mock function with given fields: ctx, requestUser
func (_m *AuthService) LogIn(ctx context.Context, requestUser dto.LogInUser) (dto.UserInfo, string, error) {
	ret := _m.Called(ctx, requestUser)

	if len(ret) == 0 {
		panic("no return value specified for LogIn")
	}

	var r0 dto.UserInfo
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.LogInUser) (dto.UserInfo, string, error)); ok {
		return rf(ctx, requestUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.LogInUser) dto.UserInfo); ok {
		r0 = rf(ctx, requestUser)
	} else {
		r0 = ret.Get(0).(dto.UserInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.LogInUser) string); ok {
		r1 = rf(ctx, requestUser)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.LogInUser) error); ok {
		r2 = rf(ctx, requestUser)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LogOut provides a mock function with given fields: ctx, sessionID
func (_m *AuthService) LogOut(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for LogOut")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshSession provides a mock function with given fields: ctx, sessionID
func (_m *AuthService) RefreshSession(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Register provides a mock function with given fields: ctx, requestUser
func (_m *AuthService) Register(ctx context.Context, requestUser dto.RegistrationUser) (dto.UserInfo, string, error) {
	ret := _m.Called(ctx, requestUser)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 dto.UserInfo
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegistrationUser) (dto.UserInfo, string, error)); ok {
		return rf(ctx, requestUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegistrationUser) dto.UserInfo); ok {
		r0 = rf(ctx, requestUser)
	} else {
		r0 = ret.Get(0).(dto.UserInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RegistrationUser) string); ok {
		r1 = rf(ctx, requestUser)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.RegistrationUser) error); ok {
		r2 = rf(ctx, requestUser)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ResetPassword provides a mock function with given fields: ctx, tokenID, newPassword
func (_m *AuthService) ResetPassword(ctx context.Context, tokenID string, newPassword string) error {
	ret := _m.Called(ctx, tokenID, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tokenID, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveRefreshTokenFroUser provides a mock function with given fields: ctx, info, token
func (_m *AuthService) SaveRefreshTokenFroUser(ctx context.Context, info dto.UserInfo, token string) error {
	ret := _m.Called(ctx, info, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshTokenFroUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserInfo, string) error); ok {
		r0 = rf(ctx, info, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendRecoveryCode provides a mock function with given fields: ctx, email
func (_m *AuthService) SendRecoveryCode(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for SendRecoveryCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCountRequests provides a mock function with given fields: ctx, config
func (_m *AuthService) UpdateCountRequests(ctx context.Context, config dto.RateLimiterConfig) (bool, error) {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCountRequests")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RateLimiterConfig) (bool, error)); ok {
		return rf(ctx, config)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RateLimiterConfig) bool); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RateLimiterConfig) error); ok {
		r1 = rf(ctx, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
