app:
  log_level: info

engine:
  addr: 0.0.0.0:8080
  graceful_shutdown_timeout: 15

redis:
  number_db: 0
  min_connections: 20
  max_connections: 100
  ping_sleep_time: 2s
  max_retries: 5

sentry:
  environment: "production"
  release: "RK3"
  service_name: "rate_limiter"
  traces_sample_rate: 1.0
  tags:
    layer: "grpc"
    team: "api-platform"
    protocol: "grpc"
  repanic: false
