// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/go-park-mail-ru/2026_1_Clac_Clac/board/internal/card/repository/dto"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CardRepository is an autogenerated mock type for the CardRepository type
type CardRepository struct {
	mock.Mock
}

// CreateCard provides a mock function with given fields: ctx, newCard
func (_m *CardRepository) CreateCard(ctx context.Context, newCard dto.NewCard) (int, error) {
	ret := _m.Called(ctx, newCard)

	if len(ret) == 0 {
		panic("no return value specified for CreateCard")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.NewCard) (int, error)); ok {
		return rf(ctx, newCard)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.NewCard) int); ok {
		r0 = rf(ctx, newCard)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.NewCard) error); ok {
		r1 = rf(ctx, newCard)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCard provides a mock function with given fields: ctx, linkCard
func (_m *CardRepository) DeleteCard(ctx context.Context, linkCard uuid.UUID) error {
	ret := _m.Called(ctx, linkCard)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, linkCard)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCard provides a mock function with given fields: ctx, linkCard
func (_m *CardRepository) GetCard(ctx context.Context, linkCard uuid.UUID) (dto.InfoCard, error) {
	ret := _m.Called(ctx, linkCard)

	if len(ret) == 0 {
		panic("no return value specified for GetCard")
	}

	var r0 dto.InfoCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.InfoCard, error)); ok {
		return rf(ctx, linkCard)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.InfoCard); ok {
		r0 = rf(ctx, linkCard)
	} else {
		r0 = ret.Get(0).(dto.InfoCard)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, linkCard)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReorderCard provides a mock function with given fields: ctx, updatingPlaceCard
func (_m *CardRepository) ReorderCard(ctx context.Context, updatingPlaceCard dto.PlaceCard) error {
	ret := _m.Called(ctx, updatingPlaceCard)

	if len(ret) == 0 {
		panic("no return value specified for ReorderCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.PlaceCard) error); ok {
		r0 = rf(ctx, updatingPlaceCard)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCardDetails provides a mock function with given fields: ctx, updatedCard
func (_m *CardRepository) UpdateCardDetails(ctx context.Context, updatedCard dto.UpdatingCardDetails) error {
	ret := _m.Called(ctx, updatedCard)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCardDetails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdatingCardDetails) error); ok {
		r0 = rf(ctx, updatedCard)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCardRepository creates a new instance of CardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardRepository {
	mock := &CardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
