// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockAuthRep

import (
	context "context"
	io "io"

	dto "github.com/go-park-mail-ru/2026_1_Clac_Clac/user/internal/user/repository/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: ctx, user
func (_m *AuthRepository) AddUser(ctx context.Context, user dto.UserInitialize) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserInitialize) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAvatarS3 provides a mock function with given fields: ctx, key
func (_m *AuthRepository) DeleteAvatarS3(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAvatarS3")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteURLAvatar provides a mock function with given fields: ctx, userLink
func (_m *AuthRepository) DeleteURLAvatar(ctx context.Context, userLink uuid.UUID) error {
	ret := _m.Called(ctx, userLink)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURLAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userLink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAvatarKey provides a mock function with given fields: ctx, userLink
func (_m *AuthRepository) GetAvatarKey(ctx context.Context, userLink uuid.UUID) (string, error) {
	ret := _m.Called(ctx, userLink)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatarKey")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, userLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, userLink)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfile provides a mock function with given fields: ctx, userLink
func (_m *AuthRepository) GetProfile(ctx context.Context, userLink uuid.UUID) (dto.UserInfoEntity, error) {
	ret := _m.Called(ctx, userLink)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 dto.UserInfoEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.UserInfoEntity, error)); ok {
		return rf(ctx, userLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.UserInfoEntity); ok {
		r0 = rf(ctx, userLink)
	} else {
		r0 = ret.Get(0).(dto.UserInfoEntity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, email
func (_m *AuthRepository) GetUser(ctx context.Context, email string) (dto.UserEntity, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 dto.UserEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dto.UserEntity, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dto.UserEntity); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(dto.UserEntity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserLink provides a mock function with given fields: ctx, email
func (_m *AuthRepository) GetUserLink(ctx context.Context, email string) (uuid.UUID, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLink")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePassword provides a mock function with given fields: ctx, userID, newPasswordHash
func (_m *AuthRepository) UpdatePassword(ctx context.Context, userID uuid.UUID, newPasswordHash string) error {
	ret := _m.Called(ctx, userID, newPasswordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, newPasswordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProfile provides a mock function with given fields: ctx, updatedInfo
func (_m *AuthRepository) UpdateProfile(ctx context.Context, updatedInfo dto.UpdatedInfo) error {
	ret := _m.Called(ctx, updatedInfo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdatedInfo) error); ok {
		r0 = rf(ctx, updatedInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadAvatarS3 provides a mock function with given fields: ctx, file, pathFile, contentType
func (_m *AuthRepository) UploadAvatarS3(ctx context.Context, file io.Reader, pathFile string, contentType string) (string, error) {
	ret := _m.Called(ctx, file, pathFile, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadAvatarS3")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) (string, error)); ok {
		return rf(ctx, file, pathFile, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) string); ok {
		r0 = rf(ctx, file, pathFile, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string, string) error); ok {
		r1 = rf(ctx, file, pathFile, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadURLAvatar provides a mock function with given fields: ctx, userLink, objectKey
func (_m *AuthRepository) UploadURLAvatar(ctx context.Context, userLink uuid.UUID, objectKey string) error {
	ret := _m.Called(ctx, userLink, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for UploadURLAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userLink, objectKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthRepository creates a new instance of AuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepository {
	mock := &AuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
