// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockSectionRep

import (
	context "context"

<<<<<<<< HEAD:board/internal/section/service/mock_section_rep/SectionRepository.go
	dto "github.com/go-park-mail-ru/2026_1_Clac_Clac/board/internal/section/repository/dto"
========
	dto "github.com/go-park-mail-ru/2026_1_Clac_Clac/monolith/internal/section/repository/dto"
>>>>>>>> feat/add-facade:monolith/internal/section/service/mock_section_rep/SectionRepository.go
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SectionRepository is an autogenerated mock type for the SectionRepository type
type SectionRepository struct {
	mock.Mock
}

// CreateSection provides a mock function with given fields: ctx, newSection
func (_m *SectionRepository) CreateSection(ctx context.Context, newSection dto.CreatingSection) (dto.FullSectionInfo, error) {
	ret := _m.Called(ctx, newSection)

	if len(ret) == 0 {
		panic("no return value specified for CreateSection")
	}

	var r0 dto.FullSectionInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreatingSection) (dto.FullSectionInfo, error)); ok {
		return rf(ctx, newSection)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreatingSection) dto.FullSectionInfo); ok {
		r0 = rf(ctx, newSection)
	} else {
		r0 = ret.Get(0).(dto.FullSectionInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreatingSection) error); ok {
		r1 = rf(ctx, newSection)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSection provides a mock function with given fields: ctx, linkSection
func (_m *SectionRepository) DeleteSection(ctx context.Context, linkSection uuid.UUID) error {
	ret := _m.Called(ctx, linkSection)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, linkSection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllSections provides a mock function with given fields: ctx, boarderLink
func (_m *SectionRepository) GetAllSections(ctx context.Context, boarderLink uuid.UUID) ([]dto.FullSectionInfo, error) {
	ret := _m.Called(ctx, boarderLink)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSections")
	}

	var r0 []dto.FullSectionInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]dto.FullSectionInfo, error)); ok {
		return rf(ctx, boarderLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []dto.FullSectionInfo); ok {
		r0 = rf(ctx, boarderLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.FullSectionInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, boarderLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCards provides a mock function with given fields: ctx, linkSection
func (_m *SectionRepository) GetCards(ctx context.Context, linkSection uuid.UUID) ([]dto.Card, error) {
	ret := _m.Called(ctx, linkSection)

	if len(ret) == 0 {
		panic("no return value specified for GetCards")
	}

	var r0 []dto.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]dto.Card, error)); ok {
		return rf(ctx, linkSection)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []dto.Card); ok {
		r0 = rf(ctx, linkSection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, linkSection)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSectionInfo provides a mock function with given fields: ctx, link
func (_m *SectionRepository) GetSectionInfo(ctx context.Context, link uuid.UUID) (dto.FullSectionInfo, error) {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for GetSectionInfo")
	}

	var r0 dto.FullSectionInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.FullSectionInfo, error)); ok {
		return rf(ctx, link)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.FullSectionInfo); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Get(0).(dto.FullSectionInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, link)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReorderSection provides a mock function with given fields: ctx, linkBoard, sectionLinks
func (_m *SectionRepository) ReorderSection(ctx context.Context, linkBoard uuid.UUID, sectionLinks []uuid.UUID) error {
	ret := _m.Called(ctx, linkBoard, sectionLinks)

	if len(ret) == 0 {
		panic("no return value specified for ReorderSection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, linkBoard, sectionLinks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSection provides a mock function with given fields: ctx, updatingSection
func (_m *SectionRepository) UpdateSection(ctx context.Context, updatingSection dto.FullSectionInfo) error {
	ret := _m.Called(ctx, updatingSection)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.FullSectionInfo) error); ok {
		r0 = rf(ctx, updatingSection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSectionRepository creates a new instance of SectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SectionRepository {
	mock := &SectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
