// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/board/v1/board.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Background    string                 `protobuf:"bytes,4,opt,name=background,proto3" json:"background,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardInfo) Reset() {
	*x = BoardInfo{}
	mi := &file_proto_board_v1_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardInfo) ProtoMessage() {}

func (x *BoardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardInfo.ProtoReflect.Descriptor instead.
func (*BoardInfo) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{0}
}

func (x *BoardInfo) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *BoardInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BoardInfo) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *BoardInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetBoards
type GetBoardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardsRequest) Reset() {
	*x = GetBoardsRequest{}
	mi := &file_proto_board_v1_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardsRequest) ProtoMessage() {}

func (x *GetBoardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardsRequest.ProtoReflect.Descriptor instead.
func (*GetBoardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{1}
}

func (x *GetBoardsRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

type GetBoardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardsInfo    []*BoardInfo           `protobuf:"bytes,1,rep,name=boards_info,json=boardsInfo,proto3" json:"boards_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardsResponse) Reset() {
	*x = GetBoardsResponse{}
	mi := &file_proto_board_v1_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardsResponse) ProtoMessage() {}

func (x *GetBoardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardsResponse.ProtoReflect.Descriptor instead.
func (*GetBoardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{2}
}

func (x *GetBoardsResponse) GetBoardsInfo() []*BoardInfo {
	if x != nil {
		return x.BoardsInfo
	}
	return nil
}

// GetBoard
type GetBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	BoardLink     string                 `protobuf:"bytes,2,opt,name=board_link,json=boardLink,proto3" json:"board_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardRequest) Reset() {
	*x = GetBoardRequest{}
	mi := &file_proto_board_v1_board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardRequest) ProtoMessage() {}

func (x *GetBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardRequest.ProtoReflect.Descriptor instead.
func (*GetBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{3}
}

func (x *GetBoardRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *GetBoardRequest) GetBoardLink() string {
	if x != nil {
		return x.BoardLink
	}
	return ""
}

type GetBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardInfo     *BoardInfo             `protobuf:"bytes,1,opt,name=board_info,json=boardInfo,proto3" json:"board_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardResponse) Reset() {
	*x = GetBoardResponse{}
	mi := &file_proto_board_v1_board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardResponse) ProtoMessage() {}

func (x *GetBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardResponse.ProtoReflect.Descriptor instead.
func (*GetBoardResponse) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{4}
}

func (x *GetBoardResponse) GetBoardInfo() *BoardInfo {
	if x != nil {
		return x.BoardInfo
	}
	return nil
}

// CreateBoard
type CreateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Background    string                 `protobuf:"bytes,4,opt,name=background,proto3" json:"background,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardRequest) Reset() {
	*x = CreateBoardRequest{}
	mi := &file_proto_board_v1_board_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardRequest) ProtoMessage() {}

func (x *CreateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardRequest.ProtoReflect.Descriptor instead.
func (*CreateBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBoardRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *CreateBoardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBoardRequest) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

type CreateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardInfo     *BoardInfo             `protobuf:"bytes,1,opt,name=board_info,json=boardInfo,proto3" json:"board_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardResponse) Reset() {
	*x = CreateBoardResponse{}
	mi := &file_proto_board_v1_board_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardResponse) ProtoMessage() {}

func (x *CreateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardResponse.ProtoReflect.Descriptor instead.
func (*CreateBoardResponse) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBoardResponse) GetBoardInfo() *BoardInfo {
	if x != nil {
		return x.BoardInfo
	}
	return nil
}

// DeleteBoard
type DeleteBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	BoardLink     string                 `protobuf:"bytes,2,opt,name=board_link,json=boardLink,proto3" json:"board_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBoardRequest) Reset() {
	*x = DeleteBoardRequest{}
	mi := &file_proto_board_v1_board_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoardRequest) ProtoMessage() {}

func (x *DeleteBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoardRequest.ProtoReflect.Descriptor instead.
func (*DeleteBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBoardRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *DeleteBoardRequest) GetBoardLink() string {
	if x != nil {
		return x.BoardLink
	}
	return ""
}

type DeleteBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBoardResponse) Reset() {
	*x = DeleteBoardResponse{}
	mi := &file_proto_board_v1_board_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoardResponse) ProtoMessage() {}

func (x *DeleteBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoardResponse.ProtoReflect.Descriptor instead.
func (*DeleteBoardResponse) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{8}
}

// UpdateBoard
type UpdateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	BoardLink     string                 `protobuf:"bytes,2,opt,name=board_link,json=boardLink,proto3" json:"board_link,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Background    string                 `protobuf:"bytes,5,opt,name=background,proto3" json:"background,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardRequest) Reset() {
	*x = UpdateBoardRequest{}
	mi := &file_proto_board_v1_board_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardRequest) ProtoMessage() {}

func (x *UpdateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardRequest.ProtoReflect.Descriptor instead.
func (*UpdateBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBoardRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *UpdateBoardRequest) GetBoardLink() string {
	if x != nil {
		return x.BoardLink
	}
	return ""
}

func (x *UpdateBoardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateBoardRequest) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

type UpdateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardResponse) Reset() {
	*x = UpdateBoardResponse{}
	mi := &file_proto_board_v1_board_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardResponse) ProtoMessage() {}

func (x *UpdateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardResponse.ProtoReflect.Descriptor instead.
func (*UpdateBoardResponse) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{10}
}

// UploadBackground
type UploadBackgroundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	BoardLink     string                 `protobuf:"bytes,2,opt,name=board_link,json=boardLink,proto3" json:"board_link,omitempty"`
	Image         []byte                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBackgroundRequest) Reset() {
	*x = UploadBackgroundRequest{}
	mi := &file_proto_board_v1_board_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBackgroundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBackgroundRequest) ProtoMessage() {}

func (x *UploadBackgroundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBackgroundRequest.ProtoReflect.Descriptor instead.
func (*UploadBackgroundRequest) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{11}
}

func (x *UploadBackgroundRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *UploadBackgroundRequest) GetBoardLink() string {
	if x != nil {
		return x.BoardLink
	}
	return ""
}

func (x *UploadBackgroundRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *UploadBackgroundRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadBackgroundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackgroundKey string                 `protobuf:"bytes,1,opt,name=background_key,json=backgroundKey,proto3" json:"background_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBackgroundResponse) Reset() {
	*x = UploadBackgroundResponse{}
	mi := &file_proto_board_v1_board_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBackgroundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBackgroundResponse) ProtoMessage() {}

func (x *UploadBackgroundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBackgroundResponse.ProtoReflect.Descriptor instead.
func (*UploadBackgroundResponse) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{12}
}

func (x *UploadBackgroundResponse) GetBackgroundKey() string {
	if x != nil {
		return x.BackgroundKey
	}
	return ""
}

// GetMembers
type GetMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardLink     string                 `protobuf:"bytes,1,opt,name=board_link,json=boardLink,proto3" json:"board_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersRequest) Reset() {
	*x = GetMembersRequest{}
	mi := &file_proto_board_v1_board_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersRequest) ProtoMessage() {}

func (x *GetMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersRequest.ProtoReflect.Descriptor instead.
func (*GetMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{13}
}

func (x *GetMembersRequest) GetBoardLink() string {
	if x != nil {
		return x.BoardLink
	}
	return ""
}

type GetMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsersLinks    []string               `protobuf:"bytes,1,rep,name=users_links,json=usersLinks,proto3" json:"users_links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersResponse) Reset() {
	*x = GetMembersResponse{}
	mi := &file_proto_board_v1_board_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersResponse) ProtoMessage() {}

func (x *GetMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_v1_board_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersResponse.ProtoReflect.Descriptor instead.
func (*GetMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_board_v1_board_proto_rawDescGZIP(), []int{14}
}

func (x *GetMembersResponse) GetUsersLinks() []string {
	if x != nil {
		return x.UsersLinks
	}
	return nil
}

var File_proto_board_v1_board_proto protoreflect.FileDescriptor

const file_proto_board_v1_board_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/board/v1/board.proto\x12\x0eproto.board.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n" +
	"\tBoardInfo\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"background\x18\x04 \x01(\tR\n" +
	"background\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"/\n" +
	"\x10GetBoardsRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\"O\n" +
	"\x11GetBoardsResponse\x12:\n" +
	"\vboards_info\x18\x01 \x03(\v2\x19.proto.board.v1.BoardInfoR\n" +
	"boardsInfo\"M\n" +
	"\x0fGetBoardRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x1d\n" +
	"\n" +
	"board_link\x18\x02 \x01(\tR\tboardLink\"L\n" +
	"\x10GetBoardResponse\x128\n" +
	"\n" +
	"board_info\x18\x01 \x01(\v2\x19.proto.board.v1.BoardInfoR\tboardInfo\"\x87\x01\n" +
	"\x12CreateBoardRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"background\x18\x04 \x01(\tR\n" +
	"background\"O\n" +
	"\x13CreateBoardResponse\x128\n" +
	"\n" +
	"board_info\x18\x01 \x01(\v2\x19.proto.board.v1.BoardInfoR\tboardInfo\"P\n" +
	"\x12DeleteBoardRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x1d\n" +
	"\n" +
	"board_link\x18\x02 \x01(\tR\tboardLink\"\x15\n" +
	"\x13DeleteBoardResponse\"\xa6\x01\n" +
	"\x12UpdateBoardRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x1d\n" +
	"\n" +
	"board_link\x18\x02 \x01(\tR\tboardLink\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"background\x18\x05 \x01(\tR\n" +
	"background\"\x15\n" +
	"\x13UpdateBoardResponse\"\x87\x01\n" +
	"\x17UploadBackgroundRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x1d\n" +
	"\n" +
	"board_link\x18\x02 \x01(\tR\tboardLink\x12\x14\n" +
	"\x05image\x18\x03 \x01(\fR\x05image\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\"A\n" +
	"\x18UploadBackgroundResponse\x12%\n" +
	"\x0ebackground_key\x18\x01 \x01(\tR\rbackgroundKey\"2\n" +
	"\x11GetMembersRequest\x12\x1d\n" +
	"\n" +
	"board_link\x18\x01 \x01(\tR\tboardLink\"5\n" +
	"\x12GetMembersResponse\x12\x1f\n" +
	"\vusers_links\x18\x01 \x03(\tR\n" +
	"usersLinks2\xf3\x04\n" +
	"\fBoardService\x12P\n" +
	"\tGetBoards\x12 .proto.board.v1.GetBoardsRequest\x1a!.proto.board.v1.GetBoardsResponse\x12M\n" +
	"\bGetBoard\x12\x1f.proto.board.v1.GetBoardRequest\x1a .proto.board.v1.GetBoardResponse\x12V\n" +
	"\vCreateBoard\x12\".proto.board.v1.CreateBoardRequest\x1a#.proto.board.v1.CreateBoardResponse\x12V\n" +
	"\vDeleteBoard\x12\".proto.board.v1.DeleteBoardRequest\x1a#.proto.board.v1.DeleteBoardResponse\x12V\n" +
	"\vUpdateBoard\x12\".proto.board.v1.UpdateBoardRequest\x1a#.proto.board.v1.UpdateBoardResponse\x12e\n" +
	"\x10UploadBackground\x12'.proto.board.v1.UploadBackgroundRequest\x1a(.proto.board.v1.UploadBackgroundResponse\x12S\n" +
	"\n" +
	"GetMembers\x12!.proto.board.v1.GetMembersRequest\x1a\".proto.board.v1.GetMembersResponseB@Z>github.com/go-park-mail-ru/2026_1_Clac_Clac/pkg/proto/board/v1b\x06proto3"

var (
	file_proto_board_v1_board_proto_rawDescOnce sync.Once
	file_proto_board_v1_board_proto_rawDescData []byte
)

func file_proto_board_v1_board_proto_rawDescGZIP() []byte {
	file_proto_board_v1_board_proto_rawDescOnce.Do(func() {
		file_proto_board_v1_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_board_v1_board_proto_rawDesc), len(file_proto_board_v1_board_proto_rawDesc)))
	})
	return file_proto_board_v1_board_proto_rawDescData
}

var file_proto_board_v1_board_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_board_v1_board_proto_goTypes = []any{
	(*BoardInfo)(nil),                // 0: proto.board.v1.BoardInfo
	(*GetBoardsRequest)(nil),         // 1: proto.board.v1.GetBoardsRequest
	(*GetBoardsResponse)(nil),        // 2: proto.board.v1.GetBoardsResponse
	(*GetBoardRequest)(nil),          // 3: proto.board.v1.GetBoardRequest
	(*GetBoardResponse)(nil),         // 4: proto.board.v1.GetBoardResponse
	(*CreateBoardRequest)(nil),       // 5: proto.board.v1.CreateBoardRequest
	(*CreateBoardResponse)(nil),      // 6: proto.board.v1.CreateBoardResponse
	(*DeleteBoardRequest)(nil),       // 7: proto.board.v1.DeleteBoardRequest
	(*DeleteBoardResponse)(nil),      // 8: proto.board.v1.DeleteBoardResponse
	(*UpdateBoardRequest)(nil),       // 9: proto.board.v1.UpdateBoardRequest
	(*UpdateBoardResponse)(nil),      // 10: proto.board.v1.UpdateBoardResponse
	(*UploadBackgroundRequest)(nil),  // 11: proto.board.v1.UploadBackgroundRequest
	(*UploadBackgroundResponse)(nil), // 12: proto.board.v1.UploadBackgroundResponse
	(*GetMembersRequest)(nil),        // 13: proto.board.v1.GetMembersRequest
	(*GetMembersResponse)(nil),       // 14: proto.board.v1.GetMembersResponse
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_proto_board_v1_board_proto_depIdxs = []int32{
	15, // 0: proto.board.v1.BoardInfo.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: proto.board.v1.GetBoardsResponse.boards_info:type_name -> proto.board.v1.BoardInfo
	0,  // 2: proto.board.v1.GetBoardResponse.board_info:type_name -> proto.board.v1.BoardInfo
	0,  // 3: proto.board.v1.CreateBoardResponse.board_info:type_name -> proto.board.v1.BoardInfo
	1,  // 4: proto.board.v1.BoardService.GetBoards:input_type -> proto.board.v1.GetBoardsRequest
	3,  // 5: proto.board.v1.BoardService.GetBoard:input_type -> proto.board.v1.GetBoardRequest
	5,  // 6: proto.board.v1.BoardService.CreateBoard:input_type -> proto.board.v1.CreateBoardRequest
	7,  // 7: proto.board.v1.BoardService.DeleteBoard:input_type -> proto.board.v1.DeleteBoardRequest
	9,  // 8: proto.board.v1.BoardService.UpdateBoard:input_type -> proto.board.v1.UpdateBoardRequest
	11, // 9: proto.board.v1.BoardService.UploadBackground:input_type -> proto.board.v1.UploadBackgroundRequest
	13, // 10: proto.board.v1.BoardService.GetMembers:input_type -> proto.board.v1.GetMembersRequest
	2,  // 11: proto.board.v1.BoardService.GetBoards:output_type -> proto.board.v1.GetBoardsResponse
	4,  // 12: proto.board.v1.BoardService.GetBoard:output_type -> proto.board.v1.GetBoardResponse
	6,  // 13: proto.board.v1.BoardService.CreateBoard:output_type -> proto.board.v1.CreateBoardResponse
	8,  // 14: proto.board.v1.BoardService.DeleteBoard:output_type -> proto.board.v1.DeleteBoardResponse
	10, // 15: proto.board.v1.BoardService.UpdateBoard:output_type -> proto.board.v1.UpdateBoardResponse
	12, // 16: proto.board.v1.BoardService.UploadBackground:output_type -> proto.board.v1.UploadBackgroundResponse
	14, // 17: proto.board.v1.BoardService.GetMembers:output_type -> proto.board.v1.GetMembersResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_board_v1_board_proto_init() }
func file_proto_board_v1_board_proto_init() {
	if File_proto_board_v1_board_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_board_v1_board_proto_rawDesc), len(file_proto_board_v1_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_board_v1_board_proto_goTypes,
		DependencyIndexes: file_proto_board_v1_board_proto_depIdxs,
		MessageInfos:      file_proto_board_v1_board_proto_msgTypes,
	}.Build()
	File_proto_board_v1_board_proto = out.File
	file_proto_board_v1_board_proto_goTypes = nil
	file_proto_board_v1_board_proto_depIdxs = nil
}
