global:
  domain: clac-clac.mooo.com

configs:
  params:
    server.insecure: "true"
    server.basehref: "/argocd"
    server.rootpath: "/argocd"

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/service.serversscheme: http
      traefik.ingress.kubernetes.io/router.priority: "100"
    pathType: Prefix
    paths:
      - /argocd
