// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockUserServiceClient

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/go-park-mail-ru/2026_1_Clac_Clac/pkg/proto/user/v1"
)

// UserServiceClient is an autogenerated mock type for the UserServiceClient type
type UserServiceClient struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) CreateUser(ctx context.Context, in *v1.CreateRequest, opts ...grpc.CallOption) (*v1.UserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *v1.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.CreateRequest, ...grpc.CallOption) (*v1.UserResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.CreateRequest, ...grpc.CallOption) *v1.UserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.CreateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAvatar provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) DeleteAvatar(ctx context.Context, in *v1.UserLinkRequest, opts ...grpc.CallOption) (*v1.DeleteAvatarResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAvatar")
	}

	var r0 *v1.DeleteAvatarResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UserLinkRequest, ...grpc.CallOption) (*v1.DeleteAvatarResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UserLinkRequest, ...grpc.CallOption) *v1.DeleteAvatarResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.DeleteAvatarResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.UserLinkRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfile provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) GetProfile(ctx context.Context, in *v1.UserLinkRequest, opts ...grpc.CallOption) (*v1.ProfileResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *v1.ProfileResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UserLinkRequest, ...grpc.CallOption) (*v1.ProfileResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UserLinkRequest, ...grpc.CallOption) *v1.ProfileResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ProfileResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.UserLinkRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfiles provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) GetProfiles(ctx context.Context, in *v1.GetProfilesRequest, opts ...grpc.CallOption) (*v1.GetProfilesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetProfiles")
	}

	var r0 *v1.GetProfilesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetProfilesRequest, ...grpc.CallOption) (*v1.GetProfilesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetProfilesRequest, ...grpc.CallOption) *v1.GetProfilesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.GetProfilesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.GetProfilesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) GetUser(ctx context.Context, in *v1.GetUserRequest, opts ...grpc.CallOption) (*v1.UserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *v1.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetUserRequest, ...grpc.CallOption) (*v1.UserResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetUserRequest, ...grpc.CallOption) *v1.UserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.GetUserRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserLink provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) GetUserLink(ctx context.Context, in *v1.GetUserLinkRequest, opts ...grpc.CallOption) (*v1.GetUserLinkResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLink")
	}

	var r0 *v1.GetUserLinkResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetUserLinkRequest, ...grpc.CallOption) (*v1.GetUserLinkResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetUserLinkRequest, ...grpc.CallOption) *v1.GetUserLinkResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.GetUserLinkResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.GetUserLinkRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessUserWithVK provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) ProcessUserWithVK(ctx context.Context, in *v1.ProcessUserVKRequest, opts ...grpc.CallOption) (*v1.ProcessUserVKResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ProcessUserWithVK")
	}

	var r0 *v1.ProcessUserVKResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ProcessUserVKRequest, ...grpc.CallOption) (*v1.ProcessUserVKResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ProcessUserVKRequest, ...grpc.CallOption) *v1.ProcessUserVKResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ProcessUserVKResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ProcessUserVKRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetPassword provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) ResetPassword(ctx context.Context, in *v1.ResetPasswordRequest, opts ...grpc.CallOption) (*v1.ResetPasswordResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 *v1.ResetPasswordResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ResetPasswordRequest, ...grpc.CallOption) (*v1.ResetPasswordResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ResetPasswordRequest, ...grpc.CallOption) *v1.ResetPasswordResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ResetPasswordResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ResetPasswordRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAvatar provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) UpdateAvatar(ctx context.Context, in *v1.UpdateAvatarRequest, opts ...grpc.CallOption) (*v1.AvatarResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAvatar")
	}

	var r0 *v1.AvatarResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UpdateAvatarRequest, ...grpc.CallOption) (*v1.AvatarResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UpdateAvatarRequest, ...grpc.CallOption) *v1.AvatarResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.AvatarResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.UpdateAvatarRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceClient) UpdateProfile(ctx context.Context, in *v1.UpdateProfileRequest, opts ...grpc.CallOption) (*v1.UpdateProfileResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *v1.UpdateProfileResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UpdateProfileRequest, ...grpc.CallOption) (*v1.UpdateProfileResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.UpdateProfileRequest, ...grpc.CallOption) *v1.UpdateProfileResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.UpdateProfileResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.UpdateProfileRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserServiceClient creates a new instance of UserServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceClient {
	mock := &UserServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
