grafana:
  enabled: true
  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"
    requests:
      memory: "64Mi"
      cpu: "10m"
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - monitor.clac-clac.ru
    tls:
      - secretName: monitoring-tls-cert
        hosts:
          - monitor.clac-clac.ru
  grafana.ini:
    server:
      domain: monitor.clac-clac.ru
      root_url: https://monitor.clac-clac.ru

prometheus:
  prometheusSpec:
    retention: 2d
    resources:
      limits:
        memory: "384Mi"
        cpu: "200m"
      requests:
        memory: "128Mi"
        cpu: "50m"
    additionalScrapeConfigs:
      - job_name: "nexus-services"
        static_configs:
          - targets:
              - "nexus-facade-service.nexus-prod.svc.cluster.local:9091"
              - "nexus-user-service.nexus-prod.svc.cluster.local:9091"
              - "nexus-board-service.nexus-prod.svc.cluster.local:9091"
              - "nexus-appeal-service.nexus-prod.svc.cluster.local:9091"
              - "nexus-authorization-service.nexus-prod.svc.cluster.local:9091"
              - "nexus-mail-sender-service.nexus-prod.svc.cluster.local:9091"
              - "nexus-rate-limiter-service.nexus-prod.svc.cluster.local:9091"

nodeExporter:
  enabled: true
  resources:
    limits:
      memory: "32Mi"
      cpu: "50m"
    requests:
      memory: "16Mi"
      cpu: "10m"

kubeStateMetrics:
  enabled: true
  resources:
    limits:
      memory: "64Mi"
      cpu: "50m"
    requests:
      memory: "32Mi"
      cpu: "10m"

alertmanager:
  enabled: false

# Disable other components to save RAM
prometheusOperator:
  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"
    requests:
      memory: "64Mi"
      cpu: "10m"
