// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: contracts/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_contracts_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{0}
}

type DeleteAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarResponse) Reset() {
	*x = DeleteAvatarResponse{}
	mi := &file_contracts_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarResponse) ProtoMessage() {}

func (x *DeleteAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarResponse.ProtoReflect.Descriptor instead.
func (*DeleteAvatarResponse) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{1}
}

type UserLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLinkRequest) Reset() {
	*x = UserLinkRequest{}
	mi := &file_contracts_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLinkRequest) ProtoMessage() {}

func (x *UserLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLinkRequest.ProtoReflect.Descriptor instead.
func (*UserLinkRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserLinkRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_contracts_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileResponse) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *ProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProfileResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProfileResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProfileResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_contracts_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *UpdateProfileRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateProfileRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FileExtension string                 `protobuf:"bytes,4,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarRequest) Reset() {
	*x = UpdateAvatarRequest{}
	mi := &file_contracts_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarRequest) ProtoMessage() {}

func (x *UpdateAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarRequest.ProtoReflect.Descriptor instead.
func (*UpdateAvatarRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAvatarRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *UpdateAvatarRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UpdateAvatarRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UpdateAvatarRequest) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

type AvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarUrl     string                 `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarResponse) Reset() {
	*x = AvatarResponse{}
	mi := &file_contracts_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarResponse) ProtoMessage() {}

func (x *AvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarResponse.ProtoReflect.Descriptor instead.
func (*AvatarResponse) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *AvatarResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type LogInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInRequest) Reset() {
	*x = LogInRequest{}
	mi := &file_contracts_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInRequest) ProtoMessage() {}

func (x *LogInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInRequest.ProtoReflect.Descriptor instead.
func (*LogInRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *LogInRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LogInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_contracts_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserResponse) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *UserResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DisplayName      string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Password         string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	RepeatedPassword string                 `protobuf:"bytes,3,opt,name=repeated_password,json=repeatedPassword,proto3" json:"repeated_password,omitempty"`
	Email            string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_contracts_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetRepeatedPassword() string {
	if x != nil {
		return x.RepeatedPassword
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLinkRequest) Reset() {
	*x = GetUserLinkRequest{}
	mi := &file_contracts_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLinkRequest) ProtoMessage() {}

func (x *GetUserLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLinkRequest.ProtoReflect.Descriptor instead.
func (*GetUserLinkRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserLinkRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLinkResponse) Reset() {
	*x = GetUserLinkResponse{}
	mi := &file_contracts_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLinkResponse) ProtoMessage() {}

func (x *GetUserLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLinkResponse.ProtoReflect.Descriptor instead.
func (*GetUserLinkResponse) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserLinkResponse) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

type ResetPasswordRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Password         string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	RepeatedPassword string                 `protobuf:"bytes,2,opt,name=repeated_password,json=repeatedPassword,proto3" json:"repeated_password,omitempty"`
	UserLink         string                 `protobuf:"bytes,3,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_contracts_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResetPasswordRequest) GetRepeatedPassword() string {
	if x != nil {
		return x.RepeatedPassword
	}
	return ""
}

func (x *ResetPasswordRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_contracts_user_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{13}
}

type VKLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VKLoginRequest) Reset() {
	*x = VKLoginRequest{}
	mi := &file_contracts_user_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VKLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VKLoginRequest) ProtoMessage() {}

func (x *VKLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VKLoginRequest.ProtoReflect.Descriptor instead.
func (*VKLoginRequest) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{14}
}

func (x *VKLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VKLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VKLoginResponse) Reset() {
	*x = VKLoginResponse{}
	mi := &file_contracts_user_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VKLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VKLoginResponse) ProtoMessage() {}

func (x *VKLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_user_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VKLoginResponse.ProtoReflect.Descriptor instead.
func (*VKLoginResponse) Descriptor() ([]byte, []int) {
	return file_contracts_user_user_proto_rawDescGZIP(), []int{15}
}

func (x *VKLoginResponse) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

var File_contracts_user_user_proto protoreflect.FileDescriptor

const file_contracts_user_user_proto_rawDesc = "" +
	"\n" +
	"\x19contracts/user/user.proto\x12\x04user\"\x17\n" +
	"\x15UpdateProfileResponse\"\x16\n" +
	"\x14DeleteAvatarResponse\".\n" +
	"\x0fUserLinkRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\"\xa8\x01\n" +
	"\x0fProfileResponse\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\"x\n" +
	"\x14UpdateProfileRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x99\x01\n" +
	"\x13UpdateAvatarRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12%\n" +
	"\x0efile_extension\x18\x04 \x01(\tR\rfileExtension\"/\n" +
	"\x0eAvatarResponse\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x01 \x01(\tR\tavatarUrl\"@\n" +
	"\fLogInRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"|\n" +
	"\fUserResponse\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"\x93\x01\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12+\n" +
	"\x11repeated_password\x18\x03 \x01(\tR\x10repeatedPassword\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"*\n" +
	"\x12GetUserLinkRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"2\n" +
	"\x13GetUserLinkResponse\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\"|\n" +
	"\x14ResetPasswordRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12+\n" +
	"\x11repeated_password\x18\x02 \x01(\tR\x10repeatedPassword\x12\x1b\n" +
	"\tuser_link\x18\x03 \x01(\tR\buserLink\"\x17\n" +
	"\x15ResetPasswordResponse\"$\n" +
	"\x0eVKLoginRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\".\n" +
	"\x0fVKLoginResponse\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink2\xd1\x04\n" +
	"\vUserService\x12:\n" +
	"\n" +
	"GetProfile\x12\x15.user.UserLinkRequest\x1a\x15.user.ProfileResponse\x12H\n" +
	"\rUpdateProfile\x12\x1a.user.UpdateProfileRequest\x1a\x1b.user.UpdateProfileResponse\x12?\n" +
	"\fUpdateAvatar\x12\x19.user.UpdateAvatarRequest\x1a\x14.user.AvatarResponse\x12A\n" +
	"\fDeleteAvatar\x12\x15.user.UserLinkRequest\x1a\x1a.user.DeleteAvatarResponse\x123\n" +
	"\tLogInUser\x12\x12.user.LogInRequest\x1a\x12.user.UserResponse\x129\n" +
	"\fRegisterUser\x12\x15.user.RegisterRequest\x1a\x12.user.UserResponse\x12B\n" +
	"\vGetUserLink\x12\x18.user.GetUserLinkRequest\x1a\x19.user.GetUserLinkResponse\x12H\n" +
	"\rResetPassword\x12\x1a.user.ResetPasswordRequest\x1a\x1b.user.ResetPasswordResponse\x12:\n" +
	"\vLoginWithVK\x12\x14.user.VKLoginRequest\x1a\x15.user.VKLoginResponseB\x1bZ\x19./pkg/contracts/user;userb\x06proto3"

var (
	file_contracts_user_user_proto_rawDescOnce sync.Once
	file_contracts_user_user_proto_rawDescData []byte
)

func file_contracts_user_user_proto_rawDescGZIP() []byte {
	file_contracts_user_user_proto_rawDescOnce.Do(func() {
		file_contracts_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_user_user_proto_rawDesc), len(file_contracts_user_user_proto_rawDesc)))
	})
	return file_contracts_user_user_proto_rawDescData
}

var file_contracts_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_contracts_user_user_proto_goTypes = []any{
	(*UpdateProfileResponse)(nil), // 0: user.UpdateProfileResponse
	(*DeleteAvatarResponse)(nil),  // 1: user.DeleteAvatarResponse
	(*UserLinkRequest)(nil),       // 2: user.UserLinkRequest
	(*ProfileResponse)(nil),       // 3: user.ProfileResponse
	(*UpdateProfileRequest)(nil),  // 4: user.UpdateProfileRequest
	(*UpdateAvatarRequest)(nil),   // 5: user.UpdateAvatarRequest
	(*AvatarResponse)(nil),        // 6: user.AvatarResponse
	(*LogInRequest)(nil),          // 7: user.LogInRequest
	(*UserResponse)(nil),          // 8: user.UserResponse
	(*RegisterRequest)(nil),       // 9: user.RegisterRequest
	(*GetUserLinkRequest)(nil),    // 10: user.GetUserLinkRequest
	(*GetUserLinkResponse)(nil),   // 11: user.GetUserLinkResponse
	(*ResetPasswordRequest)(nil),  // 12: user.ResetPasswordRequest
	(*ResetPasswordResponse)(nil), // 13: user.ResetPasswordResponse
	(*VKLoginRequest)(nil),        // 14: user.VKLoginRequest
	(*VKLoginResponse)(nil),       // 15: user.VKLoginResponse
}
var file_contracts_user_user_proto_depIdxs = []int32{
	2,  // 0: user.UserService.GetProfile:input_type -> user.UserLinkRequest
	4,  // 1: user.UserService.UpdateProfile:input_type -> user.UpdateProfileRequest
	5,  // 2: user.UserService.UpdateAvatar:input_type -> user.UpdateAvatarRequest
	2,  // 3: user.UserService.DeleteAvatar:input_type -> user.UserLinkRequest
	7,  // 4: user.UserService.LogInUser:input_type -> user.LogInRequest
	9,  // 5: user.UserService.RegisterUser:input_type -> user.RegisterRequest
	10, // 6: user.UserService.GetUserLink:input_type -> user.GetUserLinkRequest
	12, // 7: user.UserService.ResetPassword:input_type -> user.ResetPasswordRequest
	14, // 8: user.UserService.LoginWithVK:input_type -> user.VKLoginRequest
	3,  // 9: user.UserService.GetProfile:output_type -> user.ProfileResponse
	0,  // 10: user.UserService.UpdateProfile:output_type -> user.UpdateProfileResponse
	6,  // 11: user.UserService.UpdateAvatar:output_type -> user.AvatarResponse
	1,  // 12: user.UserService.DeleteAvatar:output_type -> user.DeleteAvatarResponse
	8,  // 13: user.UserService.LogInUser:output_type -> user.UserResponse
	8,  // 14: user.UserService.RegisterUser:output_type -> user.UserResponse
	11, // 15: user.UserService.GetUserLink:output_type -> user.GetUserLinkResponse
	13, // 16: user.UserService.ResetPassword:output_type -> user.ResetPasswordResponse
	15, // 17: user.UserService.LoginWithVK:output_type -> user.VKLoginResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_user_user_proto_init() }
func file_contracts_user_user_proto_init() {
	if File_contracts_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_user_user_proto_rawDesc), len(file_contracts_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_user_user_proto_goTypes,
		DependencyIndexes: file_contracts_user_user_proto_depIdxs,
		MessageInfos:      file_contracts_user_user_proto_msgTypes,
	}.Build()
	File_contracts_user_user_proto = out.File
	file_contracts_user_user_proto_goTypes = nil
	file_contracts_user_user_proto_depIdxs = nil
}
