// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: contracts/rate_limiter/rate_limiter.proto

package rate_limiter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIp        string                 `protobuf:"bytes,1,opt,name=user_ip,json=userIp,proto3" json:"user_ip,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	WindowMs      int64                  `protobuf:"varint,3,opt,name=window_ms,json=windowMs,proto3" json:"window_ms,omitempty"` // Размер окна в миллисекундах
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                       // Максимальное число запросов в окне
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateLimitRequest) Reset() {
	*x = CheckRateLimitRequest{}
	mi := &file_contracts_rate_limiter_rate_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateLimitRequest) ProtoMessage() {}

func (x *CheckRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_rate_limiter_rate_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateLimitRequest.ProtoReflect.Descriptor instead.
func (*CheckRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_contracts_rate_limiter_rate_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRateLimitRequest) GetUserIp() string {
	if x != nil {
		return x.UserIp
	}
	return ""
}

func (x *CheckRateLimitRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRateLimitRequest) GetWindowMs() int64 {
	if x != nil {
		return x.WindowMs
	}
	return 0
}

func (x *CheckRateLimitRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CheckRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exceeded      bool                   `protobuf:"varint,1,opt,name=exceeded,proto3" json:"exceeded,omitempty"` // true — лимит превышен
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateLimitResponse) Reset() {
	*x = CheckRateLimitResponse{}
	mi := &file_contracts_rate_limiter_rate_limiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateLimitResponse) ProtoMessage() {}

func (x *CheckRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_rate_limiter_rate_limiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateLimitResponse.ProtoReflect.Descriptor instead.
func (*CheckRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_contracts_rate_limiter_rate_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRateLimitResponse) GetExceeded() bool {
	if x != nil {
		return x.Exceeded
	}
	return false
}

type SetCooldownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                      // Название cooldown-а (например, "send_recovery_code")
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                                    // Email пользователя
	ExpirationMs  int64                  `protobuf:"varint,3,opt,name=expiration_ms,json=expirationMs,proto3" json:"expiration_ms,omitempty"` // Время жизни cooldown-а в миллисекундах
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCooldownRequest) Reset() {
	*x = SetCooldownRequest{}
	mi := &file_contracts_rate_limiter_rate_limiter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCooldownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCooldownRequest) ProtoMessage() {}

func (x *SetCooldownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_rate_limiter_rate_limiter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCooldownRequest.ProtoReflect.Descriptor instead.
func (*SetCooldownRequest) Descriptor() ([]byte, []int) {
	return file_contracts_rate_limiter_rate_limiter_proto_rawDescGZIP(), []int{2}
}

func (x *SetCooldownRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetCooldownRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SetCooldownRequest) GetExpirationMs() int64 {
	if x != nil {
		return x.ExpirationMs
	}
	return 0
}

type SetCooldownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`             // true — действие разрешено (первый запрос в окне)
	WaitMs        int64                  `protobuf:"varint,2,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"` // Оставшееся время ожидания в миллисекундах (если не разрешено)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCooldownResponse) Reset() {
	*x = SetCooldownResponse{}
	mi := &file_contracts_rate_limiter_rate_limiter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCooldownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCooldownResponse) ProtoMessage() {}

func (x *SetCooldownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_rate_limiter_rate_limiter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCooldownResponse.ProtoReflect.Descriptor instead.
func (*SetCooldownResponse) Descriptor() ([]byte, []int) {
	return file_contracts_rate_limiter_rate_limiter_proto_rawDescGZIP(), []int{3}
}

func (x *SetCooldownResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *SetCooldownResponse) GetWaitMs() int64 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

var File_contracts_rate_limiter_rate_limiter_proto protoreflect.FileDescriptor

const file_contracts_rate_limiter_rate_limiter_proto_rawDesc = "" +
	"\n" +
	")contracts/rate_limiter/rate_limiter.proto\x12\frate_limiter\"{\n" +
	"\x15CheckRateLimitRequest\x12\x17\n" +
	"\auser_ip\x18\x01 \x01(\tR\x06userIp\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1b\n" +
	"\twindow_ms\x18\x03 \x01(\x03R\bwindowMs\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\"4\n" +
	"\x16CheckRateLimitResponse\x12\x1a\n" +
	"\bexceeded\x18\x01 \x01(\bR\bexceeded\"c\n" +
	"\x12SetCooldownRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rexpiration_ms\x18\x03 \x01(\x03R\fexpirationMs\"H\n" +
	"\x13SetCooldownResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x17\n" +
	"\await_ms\x18\x02 \x01(\x03R\x06waitMs2\xc5\x01\n" +
	"\x12RateLimiterService\x12[\n" +
	"\x0eCheckRateLimit\x12#.rate_limiter.CheckRateLimitRequest\x1a$.rate_limiter.CheckRateLimitResponse\x12R\n" +
	"\vSetCooldown\x12 .rate_limiter.SetCooldownRequest\x1a!.rate_limiter.SetCooldownResponseB+Z)./pkg/contracts/rate_limiter;rate_limiterb\x06proto3"

var (
	file_contracts_rate_limiter_rate_limiter_proto_rawDescOnce sync.Once
	file_contracts_rate_limiter_rate_limiter_proto_rawDescData []byte
)

func file_contracts_rate_limiter_rate_limiter_proto_rawDescGZIP() []byte {
	file_contracts_rate_limiter_rate_limiter_proto_rawDescOnce.Do(func() {
		file_contracts_rate_limiter_rate_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_rate_limiter_rate_limiter_proto_rawDesc), len(file_contracts_rate_limiter_rate_limiter_proto_rawDesc)))
	})
	return file_contracts_rate_limiter_rate_limiter_proto_rawDescData
}

var file_contracts_rate_limiter_rate_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contracts_rate_limiter_rate_limiter_proto_goTypes = []any{
	(*CheckRateLimitRequest)(nil),  // 0: rate_limiter.CheckRateLimitRequest
	(*CheckRateLimitResponse)(nil), // 1: rate_limiter.CheckRateLimitResponse
	(*SetCooldownRequest)(nil),     // 2: rate_limiter.SetCooldownRequest
	(*SetCooldownResponse)(nil),    // 3: rate_limiter.SetCooldownResponse
}
var file_contracts_rate_limiter_rate_limiter_proto_depIdxs = []int32{
	0, // 0: rate_limiter.RateLimiterService.CheckRateLimit:input_type -> rate_limiter.CheckRateLimitRequest
	2, // 1: rate_limiter.RateLimiterService.SetCooldown:input_type -> rate_limiter.SetCooldownRequest
	1, // 2: rate_limiter.RateLimiterService.CheckRateLimit:output_type -> rate_limiter.CheckRateLimitResponse
	3, // 3: rate_limiter.RateLimiterService.SetCooldown:output_type -> rate_limiter.SetCooldownResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_rate_limiter_rate_limiter_proto_init() }
func file_contracts_rate_limiter_rate_limiter_proto_init() {
	if File_contracts_rate_limiter_rate_limiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_rate_limiter_rate_limiter_proto_rawDesc), len(file_contracts_rate_limiter_rate_limiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_rate_limiter_rate_limiter_proto_goTypes,
		DependencyIndexes: file_contracts_rate_limiter_rate_limiter_proto_depIdxs,
		MessageInfos:      file_contracts_rate_limiter_rate_limiter_proto_msgTypes,
	}.Build()
	File_contracts_rate_limiter_rate_limiter_proto = out.File
	file_contracts_rate_limiter_rate_limiter_proto_goTypes = nil
	file_contracts_rate_limiter_rate_limiter_proto_depIdxs = nil
}
