app:
  log_level: info
  max_text_request_size: 10240
  max_upload_image_size: 10485760
  request_timeout: 5s
  max_file_size: 10485760

engine:
  addr: 0.0.0.0:8080
  write_timeout: 15s
  read_timeout: 15s
  idle_timeout: 60s
  graceful_shutdown_timeout: 15s

cors:
  credentials: "true"
  methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
  headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-CSRF-Token"
  max_age: "864000"

csrf:
  ttl: 24h
  expire_time_convertation_base: 10
  expire_time_convertation_type_size: 64
  parts_count: 2

services:
  user:
    client:
      addr: "nexus-user-service:8080"
      timeout: 3s
      retries: 5
    handler:
      signature_type_bytes: 512
      max_read_bytes: 5242880
      max_len_name_user: 128
      max_len_description_user: 500
      max_len_password: 128
      min_len_password: 8
      max_len_name_user: 128
      valid_extensions:
        image/png:
        image/jpg:
        image/jpeg:
        image/webp:

  auth:
    client:
      addr: "nexus-authorization-service:8080"
      timeout: 10s
      retries: 5
    handler:
      max_len_password: 128
      min_len_password: 8
      session_life_time: 24h

  mail_sender:
    addr: "nexus-mail-sender-service:8080"
    timeout: 10s
    retries: 5

  board:
    client:
      addr: "nexus-board-service:8080"
      timeout: 5s
      retries: 5
      chunk_size: 1048576
    handler:
      multipart_background_file_key: "background"
      max_display_name: 128
      max_len_description: 500

  section:
    client:
      addr: "nexus-board-service:8080"
      timeout: 5s
      retries: 5
    handler:
      max_len_display_name: 128
      max_quantity_tasks: 200

  card:
    client:
      addr: "nexus-board-service:8080"
      timeout: 5s
      retries: 5
    handler:
      max_len_title: 128
      max_len_description: 500
      max_len_comment: 2000
      max_len_subtask_description: 500
      min_points: 1
      max_points: 21
      multipart_attachment_file_key: "attachment"

  rate_limiters:
    addr: "nexus-rate-limiter-service:8080"
    timeout: 2s
    retries: 5
    actions:
      login:
        limit: 10
        action: "login"
        window: 1m
        ttl: 3s
      register:
        limit: 10
        action: "register"
        window: 1h
        ttl: 3s
    cool_down_expiration: 60

  appeal:
    client:
      addr: "nexus-appeal-service:8080"
      timeout: 5s
      retries: 5
    handler:
      multipart_attachment_file_key: "attachment"
      max_len_display_name: 128
      max_len_description: 500

  sentry:
    environment: "production"
    release: "RK3"
    service_name: "facade"
    traces_sample_rate: 1.0
    tags:
      layer: "edge"
      team: "api-platform"
      protocol: "http_rest"

metrics:
  metrics_port: ":9091"
