// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockAuthSrv

import (
	context "context"

	dto "github.com/go-park-mail-ru/2026_1_Clac_Clac/user/internal/user/service/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, requestUser
func (_m *AuthService) CreateUser(ctx context.Context, requestUser dto.EntityUser) (dto.UserInfo, error) {
	ret := _m.Called(ctx, requestUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 dto.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.EntityUser) (dto.UserInfo, error)); ok {
		return rf(ctx, requestUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.EntityUser) dto.UserInfo); ok {
		r0 = rf(ctx, requestUser)
	} else {
		r0 = ret.Get(0).(dto.UserInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.EntityUser) error); ok {
		r1 = rf(ctx, requestUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAvatar provides a mock function with given fields: ctx, userLink
func (_m *AuthService) DeleteAvatar(ctx context.Context, userLink uuid.UUID) error {
	ret := _m.Called(ctx, userLink)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userLink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnsureUserByEmail provides a mock function with given fields: ctx, info
func (_m *AuthService) EnsureUserByEmail(ctx context.Context, info dto.EntityUser) (string, error) {
	ret := _m.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for EnsureUserByEmail")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.EntityUser) (string, error)); ok {
		return rf(ctx, info)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.EntityUser) string); ok {
		r0 = rf(ctx, info)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.EntityUser) error); ok {
		r1 = rf(ctx, info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfile provides a mock function with given fields: ctx, userLink
func (_m *AuthService) GetProfile(ctx context.Context, userLink uuid.UUID) (dto.UserInfo, error) {
	ret := _m.Called(ctx, userLink)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 dto.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.UserInfo, error)); ok {
		return rf(ctx, userLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.UserInfo); ok {
		r0 = rf(ctx, userLink)
	} else {
		r0 = ret.Get(0).(dto.UserInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfiles provides a mock function with given fields: ctx, userLinks
func (_m *AuthService) GetProfiles(ctx context.Context, userLinks []uuid.UUID) ([]dto.UserInfo, error) {
	ret := _m.Called(ctx, userLinks)

	if len(ret) == 0 {
		panic("no return value specified for GetProfiles")
	}

	var r0 []dto.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]dto.UserInfo, error)); ok {
		return rf(ctx, userLinks)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []dto.UserInfo); ok {
		r0 = rf(ctx, userLinks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.UserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, userLinks)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, requestUser
func (_m *AuthService) GetUser(ctx context.Context, requestUser dto.GetUserInfo) (dto.UserInfo, error) {
	ret := _m.Called(ctx, requestUser)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 dto.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.GetUserInfo) (dto.UserInfo, error)); ok {
		return rf(ctx, requestUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.GetUserInfo) dto.UserInfo); ok {
		r0 = rf(ctx, requestUser)
	} else {
		r0 = ret.Get(0).(dto.UserInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.GetUserInfo) error); ok {
		r1 = rf(ctx, requestUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserLink provides a mock function with given fields: ctx, email
func (_m *AuthService) GetUserLink(ctx context.Context, email string) (string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetPassword provides a mock function with given fields: ctx, passwordInfo
func (_m *AuthService) ResetPassword(ctx context.Context, passwordInfo dto.ResetPasswordInfo) error {
	ret := _m.Called(ctx, passwordInfo)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ResetPasswordInfo) error); ok {
		r0 = rf(ctx, passwordInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAvatar provides a mock function with given fields: ctx, avatar
func (_m *AuthService) UpdateAvatar(ctx context.Context, avatar dto.UpdatedAvatar) (string, error) {
	ret := _m.Called(ctx, avatar)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAvatar")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdatedAvatar) (string, error)); ok {
		return rf(ctx, avatar)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdatedAvatar) string); ok {
		r0 = rf(ctx, avatar)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UpdatedAvatar) error); ok {
		r1 = rf(ctx, avatar)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: ctx, updatedInfo
func (_m *AuthService) UpdateProfile(ctx context.Context, updatedInfo dto.UpdatedUserInfo) error {
	ret := _m.Called(ctx, updatedInfo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdatedUserInfo) error); ok {
		r0 = rf(ctx, updatedInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
