// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockS3

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// S3Bucket is an autogenerated mock type for the S3Bucket type
type S3Bucket struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, key
func (_m *S3Bucket) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Put provides a mock function with given fields: ctx, data, key, contentType
func (_m *S3Bucket) Put(ctx context.Context, data io.Reader, key string, contentType string) (string, error) {
	ret := _m.Called(ctx, data, key, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) (string, error)); ok {
		return rf(ctx, data, key, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) string); ok {
		r0 = rf(ctx, data, key, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string, string) error); ok {
		r1 = rf(ctx, data, key, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewS3Bucket creates a new instance of S3Bucket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3Bucket(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3Bucket {
	mock := &S3Bucket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
