// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/go-park-mail-ru/2026_1_Clac_Clac/board/internal/board/service/dto"

	io "io"

	mock "github.com/stretchr/testify/mock"

	rbac "github.com/go-park-mail-ru/2026_1_Clac_Clac/pkg/boardRbac"

	uuid "github.com/google/uuid"
)

// BoardService is an autogenerated mock type for the BoardService type
type BoardService struct {
	mock.Mock
}

// AcceptInvite provides a mock function with given fields: ctx, inviteLink, userLink
func (_m *BoardService) AcceptInvite(ctx context.Context, inviteLink uuid.UUID, userLink uuid.UUID) (dto.InviteInfo, error) {
	ret := _m.Called(ctx, inviteLink, userLink)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInvite")
	}

	var r0 dto.InviteInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (dto.InviteInfo, error)); ok {
		return rf(ctx, inviteLink, userLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) dto.InviteInfo); ok {
		r0 = rf(ctx, inviteLink, userLink)
	} else {
		r0 = ret.Get(0).(dto.InviteInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, inviteLink, userLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CloseInvite provides a mock function with given fields: ctx, inviteLink, userLink
func (_m *BoardService) CloseInvite(ctx context.Context, inviteLink uuid.UUID, userLink uuid.UUID) error {
	ret := _m.Called(ctx, inviteLink, userLink)

	if len(ret) == 0 {
		panic("no return value specified for CloseInvite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, inviteLink, userLink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBoard provides a mock function with given fields: ctx, boardInfo, authorLink
func (_m *BoardService) CreateBoard(ctx context.Context, boardInfo dto.NewBoardInfo, authorLink uuid.UUID) (dto.BoardInfo, error) {
	ret := _m.Called(ctx, boardInfo, authorLink)

	if len(ret) == 0 {
		panic("no return value specified for CreateBoard")
	}

	var r0 dto.BoardInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.NewBoardInfo, uuid.UUID) (dto.BoardInfo, error)); ok {
		return rf(ctx, boardInfo, authorLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.NewBoardInfo, uuid.UUID) dto.BoardInfo); ok {
		r0 = rf(ctx, boardInfo, authorLink)
	} else {
		r0 = ret.Get(0).(dto.BoardInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.NewBoardInfo, uuid.UUID) error); ok {
		r1 = rf(ctx, boardInfo, authorLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateInvite provides a mock function with given fields: ctx, inviteInfo, creatorLink
func (_m *BoardService) CreateInvite(ctx context.Context, inviteInfo dto.NewInviteInfo, creatorLink uuid.UUID) (dto.InviteInfo, error) {
	ret := _m.Called(ctx, inviteInfo, creatorLink)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvite")
	}

	var r0 dto.InviteInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.NewInviteInfo, uuid.UUID) (dto.InviteInfo, error)); ok {
		return rf(ctx, inviteInfo, creatorLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.NewInviteInfo, uuid.UUID) dto.InviteInfo); ok {
		r0 = rf(ctx, inviteInfo, creatorLink)
	} else {
		r0 = ret.Get(0).(dto.InviteInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.NewInviteInfo, uuid.UUID) error); ok {
		r1 = rf(ctx, inviteInfo, creatorLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBoard provides a mock function with given fields: ctx, boardLink, userLink
func (_m *BoardService) DeleteBoard(ctx context.Context, boardLink uuid.UUID, userLink uuid.UUID) error {
	ret := _m.Called(ctx, boardLink, userLink)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBoard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, boardLink, userLink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveInvites provides a mock function with given fields: ctx, boardLink, userLink
func (_m *BoardService) GetActiveInvites(ctx context.Context, boardLink uuid.UUID, userLink uuid.UUID) ([]dto.InviteInfo, error) {
	ret := _m.Called(ctx, boardLink, userLink)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveInvites")
	}

	var r0 []dto.InviteInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]dto.InviteInfo, error)); ok {
		return rf(ctx, boardLink, userLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []dto.InviteInfo); ok {
		r0 = rf(ctx, boardLink, userLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.InviteInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, boardLink, userLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBoard provides a mock function with given fields: ctx, boardLink, userLink
func (_m *BoardService) GetBoard(ctx context.Context, boardLink uuid.UUID, userLink uuid.UUID) (dto.BoardInfo, error) {
	ret := _m.Called(ctx, boardLink, userLink)

	if len(ret) == 0 {
		panic("no return value specified for GetBoard")
	}

	var r0 dto.BoardInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (dto.BoardInfo, error)); ok {
		return rf(ctx, boardLink, userLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) dto.BoardInfo); ok {
		r0 = rf(ctx, boardLink, userLink)
	} else {
		r0 = ret.Get(0).(dto.BoardInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, boardLink, userLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBoards provides a mock function with given fields: ctx, userLink
func (_m *BoardService) GetBoards(ctx context.Context, userLink uuid.UUID) ([]dto.BoardInfo, error) {
	ret := _m.Called(ctx, userLink)

	if len(ret) == 0 {
		panic("no return value specified for GetBoards")
	}

	var r0 []dto.BoardInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]dto.BoardInfo, error)); ok {
		return rf(ctx, userLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []dto.BoardInfo); ok {
		r0 = rf(ctx, userLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.BoardInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersOfBoard provides a mock function with given fields: ctx, boardLink, userLink
func (_m *BoardService) GetUsersOfBoard(ctx context.Context, boardLink uuid.UUID, userLink uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, boardLink, userLink)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersOfBoard")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, boardLink, userLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, boardLink, userLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, boardLink, userLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMemberFromBoard provides a mock function with given fields: ctx, boardLink, userLink, callerLink
func (_m *BoardService) RemoveMemberFromBoard(ctx context.Context, boardLink uuid.UUID, userLink uuid.UUID, callerLink uuid.UUID) error {
	ret := _m.Called(ctx, boardLink, userLink, callerLink)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMemberFromBoard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, boardLink, userLink, callerLink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBackground provides a mock function with given fields: ctx, file, contentType, extension, boardLink, userLink
func (_m *BoardService) UpdateBackground(ctx context.Context, file io.Reader, contentType string, extension string, boardLink uuid.UUID, userLink uuid.UUID) (string, error) {
	ret := _m.Called(ctx, file, contentType, extension, boardLink, userLink)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBackground")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string, uuid.UUID, uuid.UUID) (string, error)); ok {
		return rf(ctx, file, contentType, extension, boardLink, userLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string, uuid.UUID, uuid.UUID) string); ok {
		r0 = rf(ctx, file, contentType, extension, boardLink, userLink)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string, string, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, file, contentType, extension, boardLink, userLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBoard provides a mock function with given fields: ctx, boardInfo, userLink
func (_m *BoardService) UpdateBoard(ctx context.Context, boardInfo dto.UpdateBoardInfo, userLink uuid.UUID) error {
	ret := _m.Called(ctx, boardInfo, userLink)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBoard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateBoardInfo, uuid.UUID) error); ok {
		r0 = rf(ctx, boardInfo, userLink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMemberRole provides a mock function with given fields: ctx, boardLink, userLink, newRole, callerLink
func (_m *BoardService) UpdateMemberRole(ctx context.Context, boardLink uuid.UUID, userLink uuid.UUID, newRole rbac.Role, callerLink uuid.UUID) error {
	ret := _m.Called(ctx, boardLink, userLink, newRole, callerLink)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, rbac.Role, uuid.UUID) error); ok {
		r0 = rf(ctx, boardLink, userLink, newRole, callerLink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBoardService creates a new instance of BoardService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBoardService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BoardService {
	mock := &BoardService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
