// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockUserClient

import (
	context "context"

	domain "github.com/go-park-mail-ru/2026_1_Clac_Clac/facade/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserClient is an autogenerated mock type for the UserClient type
type UserClient struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, infoUser
func (_m *UserClient) CreateUser(ctx context.Context, infoUser domain.NewCredentialsUser) (domain.FullInfoUser, error) {
	ret := _m.Called(ctx, infoUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 domain.FullInfoUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.NewCredentialsUser) (domain.FullInfoUser, error)); ok {
		return rf(ctx, infoUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.NewCredentialsUser) domain.FullInfoUser); ok {
		r0 = rf(ctx, infoUser)
	} else {
		r0 = ret.Get(0).(domain.FullInfoUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.NewCredentialsUser) error); ok {
		r1 = rf(ctx, infoUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, entryUser
func (_m *UserClient) GetUser(ctx context.Context, entryUser domain.Credentials) (domain.FullInfoUser, error) {
	ret := _m.Called(ctx, entryUser)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.FullInfoUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Credentials) (domain.FullInfoUser, error)); ok {
		return rf(ctx, entryUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Credentials) domain.FullInfoUser); ok {
		r0 = rf(ctx, entryUser)
	} else {
		r0 = ret.Get(0).(domain.FullInfoUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Credentials) error); ok {
		r1 = rf(ctx, entryUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserLink provides a mock function with given fields: ctx, email
func (_m *UserClient) GetUserLink(ctx context.Context, email string) (uuid.UUID, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLink")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessUserWithVK provides a mock function with given fields: ctx, accessToken, email
func (_m *UserClient) ProcessUserWithVK(ctx context.Context, accessToken string, email string) (uuid.UUID, error) {
	ret := _m.Called(ctx, accessToken, email)

	if len(ret) == 0 {
		panic("no return value specified for ProcessUserWithVK")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (uuid.UUID, error)); ok {
		return rf(ctx, accessToken, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) uuid.UUID); ok {
		r0 = rf(ctx, accessToken, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accessToken, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetPassword provides a mock function with given fields: ctx, updatedPassword
func (_m *UserClient) ResetPassword(ctx context.Context, updatedPassword domain.UpdatedPassword) error {
	ret := _m.Called(ctx, updatedPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdatedPassword) error); ok {
		r0 = rf(ctx, updatedPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserClient creates a new instance of UserClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserClient {
	mock := &UserClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
