// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: contracts/profile/profile.proto

package profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_contracts_profile_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_profile_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_contracts_profile_profile_proto_rawDescGZIP(), []int{0}
}

type DeleteAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarResponse) Reset() {
	*x = DeleteAvatarResponse{}
	mi := &file_contracts_profile_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarResponse) ProtoMessage() {}

func (x *DeleteAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_profile_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarResponse.ProtoReflect.Descriptor instead.
func (*DeleteAvatarResponse) Descriptor() ([]byte, []int) {
	return file_contracts_profile_profile_proto_rawDescGZIP(), []int{1}
}

type UserLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLinkRequest) Reset() {
	*x = UserLinkRequest{}
	mi := &file_contracts_profile_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLinkRequest) ProtoMessage() {}

func (x *UserLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_profile_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLinkRequest.ProtoReflect.Descriptor instead.
func (*UserLinkRequest) Descriptor() ([]byte, []int) {
	return file_contracts_profile_profile_proto_rawDescGZIP(), []int{2}
}

func (x *UserLinkRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_contracts_profile_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_profile_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_contracts_profile_profile_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileResponse) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *ProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProfileResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProfileResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProfileResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_contracts_profile_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_profile_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_contracts_profile_profile_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *UpdateProfileRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateProfileRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserLink      string                 `protobuf:"bytes,1,opt,name=user_link,json=userLink,proto3" json:"user_link,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FileExtension string                 `protobuf:"bytes,4,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarRequest) Reset() {
	*x = UpdateAvatarRequest{}
	mi := &file_contracts_profile_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarRequest) ProtoMessage() {}

func (x *UpdateAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_profile_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarRequest.ProtoReflect.Descriptor instead.
func (*UpdateAvatarRequest) Descriptor() ([]byte, []int) {
	return file_contracts_profile_profile_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAvatarRequest) GetUserLink() string {
	if x != nil {
		return x.UserLink
	}
	return ""
}

func (x *UpdateAvatarRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UpdateAvatarRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UpdateAvatarRequest) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

type AvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarUrl     string                 `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarResponse) Reset() {
	*x = AvatarResponse{}
	mi := &file_contracts_profile_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarResponse) ProtoMessage() {}

func (x *AvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_profile_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarResponse.ProtoReflect.Descriptor instead.
func (*AvatarResponse) Descriptor() ([]byte, []int) {
	return file_contracts_profile_profile_proto_rawDescGZIP(), []int{6}
}

func (x *AvatarResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

var File_contracts_profile_profile_proto protoreflect.FileDescriptor

const file_contracts_profile_profile_proto_rawDesc = "" +
	"\n" +
	"\x1fcontracts/profile/profile.proto\x12\aprofile\"\x17\n" +
	"\x15UpdateProfileResponse\"\x16\n" +
	"\x14DeleteAvatarResponse\".\n" +
	"\x0fUserLinkRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\"\xa8\x01\n" +
	"\x0fProfileResponse\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\"x\n" +
	"\x14UpdateProfileRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x99\x01\n" +
	"\x13UpdateAvatarRequest\x12\x1b\n" +
	"\tuser_link\x18\x01 \x01(\tR\buserLink\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12%\n" +
	"\x0efile_extension\x18\x04 \x01(\tR\rfileExtension\"/\n" +
	"\x0eAvatarResponse\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x01 \x01(\tR\tavatarUrl2\xfa\x02\n" +
	"\x0eProfileService\x12@\n" +
	"\n" +
	"GetProfile\x12\x18.profile.UserLinkRequest\x1a\x18.profile.ProfileResponse\x12F\n" +
	"\x10GetProfileByLink\x12\x18.profile.UserLinkRequest\x1a\x18.profile.ProfileResponse\x12N\n" +
	"\rUpdateProfile\x12\x1d.profile.UpdateProfileRequest\x1a\x1e.profile.UpdateProfileResponse\x12E\n" +
	"\fUpdateAvatar\x12\x1c.profile.UpdateAvatarRequest\x1a\x17.profile.AvatarResponse\x12G\n" +
	"\fDeleteAvatar\x12\x18.profile.UserLinkRequest\x1a\x1d.profile.DeleteAvatarResponseB\x17Z\x15./pkg/profile;profileb\x06proto3"

var (
	file_contracts_profile_profile_proto_rawDescOnce sync.Once
	file_contracts_profile_profile_proto_rawDescData []byte
)

func file_contracts_profile_profile_proto_rawDescGZIP() []byte {
	file_contracts_profile_profile_proto_rawDescOnce.Do(func() {
		file_contracts_profile_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_profile_profile_proto_rawDesc), len(file_contracts_profile_profile_proto_rawDesc)))
	})
	return file_contracts_profile_profile_proto_rawDescData
}

var file_contracts_profile_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_contracts_profile_profile_proto_goTypes = []any{
	(*UpdateProfileResponse)(nil), // 0: profile.UpdateProfileResponse
	(*DeleteAvatarResponse)(nil),  // 1: profile.DeleteAvatarResponse
	(*UserLinkRequest)(nil),       // 2: profile.UserLinkRequest
	(*ProfileResponse)(nil),       // 3: profile.ProfileResponse
	(*UpdateProfileRequest)(nil),  // 4: profile.UpdateProfileRequest
	(*UpdateAvatarRequest)(nil),   // 5: profile.UpdateAvatarRequest
	(*AvatarResponse)(nil),        // 6: profile.AvatarResponse
}
var file_contracts_profile_profile_proto_depIdxs = []int32{
	2, // 0: profile.ProfileService.GetProfile:input_type -> profile.UserLinkRequest
	2, // 1: profile.ProfileService.GetProfileByLink:input_type -> profile.UserLinkRequest
	4, // 2: profile.ProfileService.UpdateProfile:input_type -> profile.UpdateProfileRequest
	5, // 3: profile.ProfileService.UpdateAvatar:input_type -> profile.UpdateAvatarRequest
	2, // 4: profile.ProfileService.DeleteAvatar:input_type -> profile.UserLinkRequest
	3, // 5: profile.ProfileService.GetProfile:output_type -> profile.ProfileResponse
	3, // 6: profile.ProfileService.GetProfileByLink:output_type -> profile.ProfileResponse
	0, // 7: profile.ProfileService.UpdateProfile:output_type -> profile.UpdateProfileResponse
	6, // 8: profile.ProfileService.UpdateAvatar:output_type -> profile.AvatarResponse
	1, // 9: profile.ProfileService.DeleteAvatar:output_type -> profile.DeleteAvatarResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_profile_profile_proto_init() }
func file_contracts_profile_profile_proto_init() {
	if File_contracts_profile_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_profile_profile_proto_rawDesc), len(file_contracts_profile_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_profile_profile_proto_goTypes,
		DependencyIndexes: file_contracts_profile_profile_proto_depIdxs,
		MessageInfos:      file_contracts_profile_profile_proto_msgTypes,
	}.Build()
	File_contracts_profile_profile_proto = out.File
	file_contracts_profile_profile_proto_goTypes = nil
	file_contracts_profile_profile_proto_depIdxs = nil
}
