// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/appeal/v1/appeal.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppealService_CreateAppeal_FullMethodName       = "/proto.appeal.v1.AppealService/CreateAppeal"
	AppealService_GetAppeals_FullMethodName         = "/proto.appeal.v1.AppealService/GetAppeals"
	AppealService_UploadAttachment_FullMethodName   = "/proto.appeal.v1.AppealService/UploadAttachment"
	AppealService_DeleteAppeal_FullMethodName       = "/proto.appeal.v1.AppealService/DeleteAppeal"
	AppealService_GetStats_FullMethodName           = "/proto.appeal.v1.AppealService/GetStats"
	AppealService_ChangeAppealStatus_FullMethodName = "/proto.appeal.v1.AppealService/ChangeAppealStatus"
)

// AppealServiceClient is the client API for AppealService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppealServiceClient interface {
	CreateAppeal(ctx context.Context, in *CreateAppealRequest, opts ...grpc.CallOption) (*CreateAppealResponse, error)
	GetAppeals(ctx context.Context, in *GetAppealsRequest, opts ...grpc.CallOption) (*GetAppealsResponse, error)
	UploadAttachment(ctx context.Context, in *UploadAttachmentRequest, opts ...grpc.CallOption) (*UploadAttachmentResponse, error)
	DeleteAppeal(ctx context.Context, in *DeleteAppealRequest, opts ...grpc.CallOption) (*DeleteAppealResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	ChangeAppealStatus(ctx context.Context, in *ChangeAppealStatusRequest, opts ...grpc.CallOption) (*ChangeAppealStatusResponse, error)
}

type appealServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppealServiceClient(cc grpc.ClientConnInterface) AppealServiceClient {
	return &appealServiceClient{cc}
}

func (c *appealServiceClient) CreateAppeal(ctx context.Context, in *CreateAppealRequest, opts ...grpc.CallOption) (*CreateAppealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAppealResponse)
	err := c.cc.Invoke(ctx, AppealService_CreateAppeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appealServiceClient) GetAppeals(ctx context.Context, in *GetAppealsRequest, opts ...grpc.CallOption) (*GetAppealsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppealsResponse)
	err := c.cc.Invoke(ctx, AppealService_GetAppeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appealServiceClient) UploadAttachment(ctx context.Context, in *UploadAttachmentRequest, opts ...grpc.CallOption) (*UploadAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAttachmentResponse)
	err := c.cc.Invoke(ctx, AppealService_UploadAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appealServiceClient) DeleteAppeal(ctx context.Context, in *DeleteAppealRequest, opts ...grpc.CallOption) (*DeleteAppealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAppealResponse)
	err := c.cc.Invoke(ctx, AppealService_DeleteAppeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appealServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, AppealService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appealServiceClient) ChangeAppealStatus(ctx context.Context, in *ChangeAppealStatusRequest, opts ...grpc.CallOption) (*ChangeAppealStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeAppealStatusResponse)
	err := c.cc.Invoke(ctx, AppealService_ChangeAppealStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppealServiceServer is the server API for AppealService service.
// All implementations must embed UnimplementedAppealServiceServer
// for forward compatibility.
type AppealServiceServer interface {
	CreateAppeal(context.Context, *CreateAppealRequest) (*CreateAppealResponse, error)
	GetAppeals(context.Context, *GetAppealsRequest) (*GetAppealsResponse, error)
	UploadAttachment(context.Context, *UploadAttachmentRequest) (*UploadAttachmentResponse, error)
	DeleteAppeal(context.Context, *DeleteAppealRequest) (*DeleteAppealResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	ChangeAppealStatus(context.Context, *ChangeAppealStatusRequest) (*ChangeAppealStatusResponse, error)
	mustEmbedUnimplementedAppealServiceServer()
}

// UnimplementedAppealServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppealServiceServer struct{}

func (UnimplementedAppealServiceServer) CreateAppeal(context.Context, *CreateAppealRequest) (*CreateAppealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAppeal not implemented")
}
func (UnimplementedAppealServiceServer) GetAppeals(context.Context, *GetAppealsRequest) (*GetAppealsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppeals not implemented")
}
func (UnimplementedAppealServiceServer) UploadAttachment(context.Context, *UploadAttachmentRequest) (*UploadAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAttachment not implemented")
}
func (UnimplementedAppealServiceServer) DeleteAppeal(context.Context, *DeleteAppealRequest) (*DeleteAppealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAppeal not implemented")
}
func (UnimplementedAppealServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedAppealServiceServer) ChangeAppealStatus(context.Context, *ChangeAppealStatusRequest) (*ChangeAppealStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeAppealStatus not implemented")
}
func (UnimplementedAppealServiceServer) mustEmbedUnimplementedAppealServiceServer() {}
func (UnimplementedAppealServiceServer) testEmbeddedByValue()                       {}

// UnsafeAppealServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppealServiceServer will
// result in compilation errors.
type UnsafeAppealServiceServer interface {
	mustEmbedUnimplementedAppealServiceServer()
}

func RegisterAppealServiceServer(s grpc.ServiceRegistrar, srv AppealServiceServer) {
	// If the following call panics, it indicates UnimplementedAppealServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppealService_ServiceDesc, srv)
}

func _AppealService_CreateAppeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServiceServer).CreateAppeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppealService_CreateAppeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServiceServer).CreateAppeal(ctx, req.(*CreateAppealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppealService_GetAppeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServiceServer).GetAppeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppealService_GetAppeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServiceServer).GetAppeals(ctx, req.(*GetAppealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppealService_UploadAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServiceServer).UploadAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppealService_UploadAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServiceServer).UploadAttachment(ctx, req.(*UploadAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppealService_DeleteAppeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServiceServer).DeleteAppeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppealService_DeleteAppeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServiceServer).DeleteAppeal(ctx, req.(*DeleteAppealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppealService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppealService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppealService_ChangeAppealStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAppealStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServiceServer).ChangeAppealStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppealService_ChangeAppealStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServiceServer).ChangeAppealStatus(ctx, req.(*ChangeAppealStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppealService_ServiceDesc is the grpc.ServiceDesc for AppealService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppealService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.appeal.v1.AppealService",
	HandlerType: (*AppealServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAppeal",
			Handler:    _AppealService_CreateAppeal_Handler,
		},
		{
			MethodName: "GetAppeals",
			Handler:    _AppealService_GetAppeals_Handler,
		},
		{
			MethodName: "UploadAttachment",
			Handler:    _AppealService_UploadAttachment_Handler,
		},
		{
			MethodName: "DeleteAppeal",
			Handler:    _AppealService_DeleteAppeal_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _AppealService_GetStats_Handler,
		},
		{
			MethodName: "ChangeAppealStatus",
			Handler:    _AppealService_ChangeAppealStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/appeal/v1/appeal.proto",
}
