// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockServiceSender

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ServiceSender is an autogenerated mock type for the ServiceSender type
type ServiceSender struct {
	mock.Mock
}

// CheckRecoveryCode provides a mock function with given fields: ctx, tokenID
func (_m *ServiceSender) CheckRecoveryCode(ctx context.Context, tokenID string) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for CheckRecoveryCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserLink provides a mock function with given fields: ctx, tokenID
func (_m *ServiceSender) GetUserLink(ctx context.Context, tokenID string) (string, error) {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, tokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendRecoveryCode provides a mock function with given fields: ctx, userLink, email
func (_m *ServiceSender) SendRecoveryCode(ctx context.Context, userLink uuid.UUID, email string) error {
	ret := _m.Called(ctx, userLink, email)

	if len(ret) == 0 {
		panic("no return value specified for SendRecoveryCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userLink, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServiceSender creates a new instance of ServiceSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceSender {
	mock := &ServiceSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
