s3_avatars:
  valid_extensions:
    image/png:
    image/jpg:
    image/jpeg:
    image/webp:

database:
  min_connections: 2
  max_connections: 10
  max_connection_lifetime: 1h
  max_health_check_period: 30s
  ping_sleep_time: 2s
  time_out: 5s
  max_retries: 5

redis:
  number_db: 0
  min_connections: 20
  max_connections: 100
  ping_sleep_time: 2s
  max_retries: 5

auth:
  service:
    session_life_time: 24h
    count_retries: 3
  handler:
    session_life_time: 24h
    max_len_password: 128
    min_len_password: 8

profile:
  handler:
    siganature_type_bytes: 512
    max_read_bytes: 5242880
    max_len_name_user: 128
    max_len_description_user: 500

grpc:
  port: "50052"
