// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockCSRFUC

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CSRFUsecase is an autogenerated mock type for the CSRFUsecase type
type CSRFUsecase struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx, sessionID, token
func (_m *CSRFUsecase) Check(ctx context.Context, sessionID string, token string) error {
	ret := _m.Called(ctx, sessionID, token)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sessionID, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Generate provides a mock function with given fields: ctx, sessionID, expireAt
func (_m *CSRFUsecase) Generate(ctx context.Context, sessionID string, expireAt int64) (string, error) {
	ret := _m.Called(ctx, sessionID, expireAt)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (string, error)); ok {
		return rf(ctx, sessionID, expireAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) string); ok {
		r0 = rf(ctx, sessionID, expireAt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, sessionID, expireAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpireTime provides a mock function with given fields: ctx
func (_m *CSRFUsecase) GetExpireTime(ctx context.Context) time.Time {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExpireTime")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(context.Context) time.Time); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// NewCSRFUsecase creates a new instance of CSRFUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCSRFUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CSRFUsecase {
	mock := &CSRFUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
