// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: contracts/mail_sender/mail_sender.proto

package mail_sender

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MailSenderService_SendRecoveryCode_FullMethodName     = "/mail.MailSenderService/SendRecoveryCode"
	MailSenderService_CheckRecoveryCode_FullMethodName    = "/mail.MailSenderService/CheckRecoveryCode"
	MailSenderService_ExchangeTokenForUser_FullMethodName = "/mail.MailSenderService/ExchangeTokenForUser"
)

// MailSenderServiceClient is the client API for MailSenderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис для отправки email-сообщений пользователям
type MailSenderServiceClient interface {
	// Генерация и отправка 6-значного кода на почту
	SendRecoveryCode(ctx context.Context, in *SendRecoveryCodeRequest, opts ...grpc.CallOption) (*SendRecoveryCodeResponse, error)
	// Проверка 6-значного кода и выдача безопасного токена (Reset Token)
	CheckRecoveryCode(ctx context.Context, in *CheckRecoveryCodeRequest, opts ...grpc.CallOption) (*CheckRecoveryCodeResponse, error)
	// Обмен токена на UserLink перед сменой пароля
	ExchangeTokenForUser(ctx context.Context, in *ExchangeTokenRequest, opts ...grpc.CallOption) (*ExchangeTokenResponse, error)
}

type mailSenderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailSenderServiceClient(cc grpc.ClientConnInterface) MailSenderServiceClient {
	return &mailSenderServiceClient{cc}
}

func (c *mailSenderServiceClient) SendRecoveryCode(ctx context.Context, in *SendRecoveryCodeRequest, opts ...grpc.CallOption) (*SendRecoveryCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendRecoveryCodeResponse)
	err := c.cc.Invoke(ctx, MailSenderService_SendRecoveryCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailSenderServiceClient) CheckRecoveryCode(ctx context.Context, in *CheckRecoveryCodeRequest, opts ...grpc.CallOption) (*CheckRecoveryCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckRecoveryCodeResponse)
	err := c.cc.Invoke(ctx, MailSenderService_CheckRecoveryCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailSenderServiceClient) ExchangeTokenForUser(ctx context.Context, in *ExchangeTokenRequest, opts ...grpc.CallOption) (*ExchangeTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeTokenResponse)
	err := c.cc.Invoke(ctx, MailSenderService_ExchangeTokenForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailSenderServiceServer is the server API for MailSenderService service.
// All implementations must embed UnimplementedMailSenderServiceServer
// for forward compatibility.
//
// Сервис для отправки email-сообщений пользователям
type MailSenderServiceServer interface {
	// Генерация и отправка 6-значного кода на почту
	SendRecoveryCode(context.Context, *SendRecoveryCodeRequest) (*SendRecoveryCodeResponse, error)
	// Проверка 6-значного кода и выдача безопасного токена (Reset Token)
	CheckRecoveryCode(context.Context, *CheckRecoveryCodeRequest) (*CheckRecoveryCodeResponse, error)
	// Обмен токена на UserLink перед сменой пароля
	ExchangeTokenForUser(context.Context, *ExchangeTokenRequest) (*ExchangeTokenResponse, error)
	mustEmbedUnimplementedMailSenderServiceServer()
}

// UnimplementedMailSenderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMailSenderServiceServer struct{}

func (UnimplementedMailSenderServiceServer) SendRecoveryCode(context.Context, *SendRecoveryCodeRequest) (*SendRecoveryCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRecoveryCode not implemented")
}
func (UnimplementedMailSenderServiceServer) CheckRecoveryCode(context.Context, *CheckRecoveryCodeRequest) (*CheckRecoveryCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckRecoveryCode not implemented")
}
func (UnimplementedMailSenderServiceServer) ExchangeTokenForUser(context.Context, *ExchangeTokenRequest) (*ExchangeTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeTokenForUser not implemented")
}
func (UnimplementedMailSenderServiceServer) mustEmbedUnimplementedMailSenderServiceServer() {}
func (UnimplementedMailSenderServiceServer) testEmbeddedByValue()                           {}

// UnsafeMailSenderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailSenderServiceServer will
// result in compilation errors.
type UnsafeMailSenderServiceServer interface {
	mustEmbedUnimplementedMailSenderServiceServer()
}

func RegisterMailSenderServiceServer(s grpc.ServiceRegistrar, srv MailSenderServiceServer) {
	// If the following call panics, it indicates UnimplementedMailSenderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MailSenderService_ServiceDesc, srv)
}

func _MailSenderService_SendRecoveryCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRecoveryCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailSenderServiceServer).SendRecoveryCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailSenderService_SendRecoveryCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailSenderServiceServer).SendRecoveryCode(ctx, req.(*SendRecoveryCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailSenderService_CheckRecoveryCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRecoveryCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailSenderServiceServer).CheckRecoveryCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailSenderService_CheckRecoveryCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailSenderServiceServer).CheckRecoveryCode(ctx, req.(*CheckRecoveryCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailSenderService_ExchangeTokenForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailSenderServiceServer).ExchangeTokenForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailSenderService_ExchangeTokenForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailSenderServiceServer).ExchangeTokenForUser(ctx, req.(*ExchangeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MailSenderService_ServiceDesc is the grpc.ServiceDesc for MailSenderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailSenderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mail.MailSenderService",
	HandlerType: (*MailSenderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRecoveryCode",
			Handler:    _MailSenderService_SendRecoveryCode_Handler,
		},
		{
			MethodName: "CheckRecoveryCode",
			Handler:    _MailSenderService_CheckRecoveryCode_Handler,
		},
		{
			MethodName: "ExchangeTokenForUser",
			Handler:    _MailSenderService_ExchangeTokenForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts/mail_sender/mail_sender.proto",
}
