name: Auto Deploy

on:
  push:
    branches:
      - fix/ci-cd-deploy-workflows
    paths:
      - "deployments/**"
      - "pkg/**"
      - "**/*.go"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      has_changes: ${{ steps.set-matrix.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            shared:
              - 'pkg/**'
            appeal:
              - 'appeal/**'
              - 'deployments/appeal/**'
            authorization:
              - 'authorization/**'
              - 'deployments/authorization/**'
            board:
              - 'board/**'
              - 'deployments/board/**'
            facade:
              - 'facade/**'
              - 'deployments/facade/**'
              - 'docs/**'
            mail_sender:
              - 'mail_sender/**'
              - 'deployments/mail_sender/**'
            rate_limiter:
              - 'rate_limiter/**'
              - 'deployments/rate_limiter/**'
            user:
              - 'user/**'
              - 'deployments/user/**'

      - name: Generate Build Matrix
        id: set-matrix
        run: |
          if [[ "${{ steps.filter.outputs.shared }}" == 'true' ]]; then
            echo 'matrix=["appeal", "authorization", "board", "facade", "mail_sender", "rate_limiter", "user"]' >> $GITHUB_OUTPUT
            echo 'has_changes=true' >> $GITHUB_OUTPUT
          else
            CHANGES='${{ steps.filter.outputs.changes }}'
            echo "matrix=$CHANGES" >> $GITHUB_OUTPUT

            if [[ "$CHANGES" == "[]" ]]; then
              echo 'has_changes=false' >> $GITHUB_OUTPUT
            else
              echo 'has_changes=true' >> $GITHUB_OUTPUT
            fi
          fi

  run-deployment:
    needs: detect-changes
    if: needs.detect-changes.outputs.has_changes == 'true'
    uses: ./.github/workflows/build-and-update-chart.yaml
    with:
      matrix_services: ${{ needs.detect-changes.outputs.matrix }}
      target_revision: "fix/ci-cd-deploy-workflows"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
