name: Check Generated Code Consistency

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
          cache: true

      - name: Install Go Dependencies
        run: |
          go install github.com/mailru/easyjson/easyjson@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@1.6.2
          go install github.com/vektra/mockery/v2@latest

      - name: Install protoc
        run: |
          PROTOC_VERSION=34.1
          curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip"
          sudo unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local
          sudo chmod +x /usr/local/bin/protoc

      - name: Generate Mocks
        run: go generate ./...

      - name: Generate Easyjson
        run: make easyjson

      - name: Generate Proto
        run: make proto

      - name: Check diff
        run: |
          git diff --exit-code || \
          (echo "::error::Generated files are out of sync. Run 'make proto', 'make easyjson' and 'go generate ./...' locally." && exit 1)
